streamnative/kop

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
when get partitioned topic error,  change the log level from debug to error
> Optimize log level

- DEVELOP.md
- README.md
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
add config for allowAutoTopicCreationType=partitioned in doc
> add config for allowAutoTopicCreationType=partitioned in doc

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
The ConcurrentHashMap for responsesQueue in KafkaCommandDecoder is redundant, one channel should only need 1 queue.
> remove dup quque map in KafkaCommandDecoder

- README.md
clear KoP configuration tab dup item
> Hotfix: readme

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
> #147 fix OutOfDirectoryMemoryError

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
optimize for #134  including the following aspects:
1. recordToEntry paralleled
2. publish message to bookie asynchronous
In our environment, produce delay is about one-fifth of the previous
> Issue 134: produce optimize

- .github/workflows/release.yml
fix release action triggered 3 times
> [github action] fix release action triggered 3 times

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
parallel for the reading message, it could improve about 20% throughput.
> parallel for reading message

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
> fix oom error

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
add publish time for kafka records to enable seek offset by time
Fix #171
> add publish time for kafka records to enable seek offset by time

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
support create topic with configed partition number.  Fix #173
> support create topic with configed partition number

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
**Fixes:**
#166 #153 #99 
**Issue:**
KoP uses [Kafka-2.0.0](https://github.com/streamnative/kop/blob/78d9ba3487d4d7c85a5d667d45d9b38aaa7c824f/pom.xml#L46) which supports [API_VERSION's](https://kafka.apache.org/protocol.html#The_Messages_ApiVersions) **0** --> **2**
When **_Kafka-Clients-2.4.x+_**(using `API_VERSION:  3`) connects to KoP, it panics and following error stack is observed:
`10:22:23.281 [pulsar-io-22-4] ERROR io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - error to get Response ByteBuf:
java.lang.IllegalArgumentException: Invalid version for API key API_VERSIONS: 3
at org.apache.kafka.common.protocol.ApiKeys.schemaFor(ApiKeys.java:312) ~[?:?]
at org.apache.kafka.common.protocol.ApiKeys.responseSchema(ApiKeys.java:286) ~[?:?]
at …
> Support for Kafka-Client versions 2.4.x and above

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaService.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
- pom.xml
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/CommitOffsetBacklogTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Current version of KoP is not compatible with Pulsar 2.6.1, update the dependency to support it.
> Support Pulsar 2.6.1

- kafka-impl/pom.xml
- pom.xml
- tests/pom.xml
Bump version to 0.3.1-SNAPSHOT
> Bump version to 0.3.1-SNAPSHOT

- tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
`assertTrue` is hard to debug test failure for verifying equation
> Replace assertTrue to assertEquals

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestTypeTest.java
> Support consume compressed messages from Pulsar producer

- integrations/build.sh
- integrations/kafka-client/Dockerfile
- integrations/kafka-client/pom.xml
- integrations/kafka-client/src/main/java/Main.java
- integrations/kafka-client/src/main/resources/simplelogger.properties
- integrations/publish.sh
Add Kafka client docker images that cover version 1.x.0 to 2.y.0 (x = 0 to 1 y = 0 to 6) for integration tests.
> Add kafka-client docker images

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
bug fix for https://github.com/streamnative/kop/issues/202
> fix fetch offset when topic is null

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
speed up entriesToRecords for consuming multi entries
> speed up entriesToRecords for consuming multi entries

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
bug fix for https://github.com/streamnative/kop/issues/214
> use compatible magic value by apiVersion

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
keep offset monotonically increase, related  to https://github.com/streamnative/kop/issues/219
> keep offset monotonically increase

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottleTest.java
#222 
Support publish buffer throttle for kop .
> Support publish buffer throttle for kop

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
> change channel writable to debug  to avoid disk full

- tests/pom.xml
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaStreamsTest.java
This PR adds a unit test for Kafka Streams.
> Add unit test for Kafka Streams

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
> change listOffset log level to debug

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
> add kop address cache to prevent query zk each time

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
make allowAutoTopicCreation work
> make allowAutoTopicCreation work

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
> update lookup cache when onload & unload

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
> change auto read log to debug

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
Fix #277, using the first entry, index 0 as the base offset
> using the first entry, index 0 as base offset

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduce.java
> make ready() more stable

- pom.xml
fix #289
upgrade pulsar dependency from `2.8.0-rc-202012200040` to `2.8.0-rc-202012242230`
> upgrade pulsar dependency

- kafka-impl/pom.xml
- pom.xml
- tests/pom.xml
**Motivation**
Verify the latest pulsar
> Bump pulsar version and project version to 2.7.0.3-rc

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
fix #329 
fix highwatermark and logendoffset error
> fix highwatermark and logendoffset error

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeKafkaFormatTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimePulsarFormatTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
fix #326 
support publishtime for message of kakfa entry format
> support publishtime for message of kafka entry format

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
Thread sync problem.
Simple change. In order to keep CI stable.
It can be optimized later.
> Fix transaction ci fail problem

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetFinder.java
> format log print

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
> fix remove consumer error if the broker restart

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
> remove lookup and address cache if can not get broker address when a broker node lost

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
fixes #357
1,  remove `retFuture.complete(null)` to avoid get null cache.
2,  remove `backoff schedule `  because it will look up next time if can not get the `persistentTopic`.
> optimize lookupBroker to avoid get null cache

- README.md
[doc] update maintainer to include yunze & jia
> [doc] update maintainer to include yunze & jia

- README.md
- Add Pierre as the Maintainer
- sort name by a-z order
> [doc] Add Pierre as the Maintainer

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
- kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Currently KoP created `__consumer_offsets` repeatedly, the `ConflictException` will be thrown after https://github.com/apache/pulsar/pull/9342. Though it doesn't affect the usage because the `ConflictException` is treated as the concurrent issue and will be swallowed, it could cause some unnecessary logs. So this PR remove the redundant partition creation code.
Another issue is that when `__consumer_offsets` already exists, the existed partition will be created because the partition returned by broker contains `persistent://` prefix but the topics in `offsetPartitionSet` don't. This PR use `KopTopic` to avoid the topic name dismatch.
> Avoid unexpected ConflictException when metadata is created

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
> to fix the NPE if TransactionCoordinator disabled

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManager.java
fix #393, add ACL when creating node to avoid MarshallingError
> add ACL when creating node to avoid MarshallingError

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
> support __consumer_offsets topic compaction

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ErrorsAndData.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionConfig.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionLog.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ProducerIdAndEpoch.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
Fixes #376 
KoP Transaction state management optimization
> [Transaction] KoP Transaction state management optimization

- docs/security.md
> [Doc] Add KoP authentication

- kafka-impl/pom.xml
- pom.xml
- tests/pom.xml
> Revert pulsar version 2.7.1.0

- kafka-impl/pom.xml
- pom.xml
- tests/pom.xml
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
verify 2.7.1.1-rc-202103251930
> verify 2.7.1.1-rc-202103251930

- kafka-impl/pom.xml
- pom.xml
- tests/pom.xml
> Bump pulsar to `2.7.1.1`

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
- kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
> add retention policy for offset topic

- docs/configuration.md
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
> prevent queue too large and request timeout

- docs/configuration.md
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
> remove enableGroupCoordinator

- kafka-impl/src/assemble/bin.xml
> remove duplicate license

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
> [FEATURE] add metrics related to FETCH request

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
Fixes #479 
The NPE is introduced from https://github.com/streamnative/kop/pull/467. When the message read stats is recorded, the `recycle()` method of `MessageFetchContext` may have already been called and the `requestHandler` will become null after that, then the NPE happens.
This PR uses a simple way to fix it by extending the lifetime of `messageReadStats`. We can verify the fix by checking the output of a test like `BasicEndToEndKafkaTest#testNullValueMessages` and no NPE error logs will be found.
> Fix NPE in MessageFetchContext

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
Recently In test environment, NPE happened
> 06:45:22.417 [pulsar-io-28-18] ERROR io.streamnative.pulsar.handlers.kop.KafkaTopicManager - [[id: 0x00282baf, L:/10.0.0.44:9092 ! R:/10.0.0.175:48168]] Failed to close KafkaTopicManager. exception:
java.lang.NullPointerException: null
>        at org.apache.pulsar.broker.service.AbstractTopic.removeProducer(AbstractTopic.java:681) ~[org.apache.pulsar-pulsar-broker-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
>        at io.streamnative.pulsar.handlers.kop.KafkaTopicManager.close(KafkaTopicManager.java:314) [pulsar-protocol-handler-kafka-2.8.0-SNAPSHOT.nar-unpacked/:?]
It's triggered in `KafkaTopicManager#close`
```
if (references.get(topicName) != null) {
PersistentTopic persistentTopic = topicFuture.get();
if (persistentTopic != null) { …
```
> Avoid NPE when removing Producer from the associated PersistentTopic

- README.md
Re-structure the readme
- What is Kop and its benefits
- What's New in KoP 2.8.0
- Version compatibility
- Get Started
- How to use KoP in details
- Project maintainer
> [docs] Update KoP README 

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/CoordinatorStats.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusTextFormatUtil.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
1. add metrics for coordinator and offsetAcker
2. fix metrics provider bug
> add metrics for offset commit

- kafka-impl/pom.xml
- pom.xml
- tests/pom.xml
> Revert "Bump pulsar version to 2.7.2.3"

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
Fixes #546 
After the FETCH handler refactor in #538 , there's a thread safety problem when accessing `decodeResults` because each `DecodeResult` object is created in the callback of each partition's future and these callbacks may be not executed in the same thread. So when there're many partitions, accessing `decodeResults` is not thread-safe.
Before #538, the implementation just waits until all partitions' read completed, then collects the `DecodeResult` to a list. So using an `ArrayList` was thread safe before.
Use `ConcurrentLinkedQueue` as the container type of `decodeResults` for thread safety.
> Make DecodeResult list thread safe

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetResetTest.java
Resolved #530 
This PR implements the offset out-of-range checking and handles the exceptions for kafka-client.
> enable offset out-of-range checking

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
> throw IllegalStateException if group/transaction coordinators fail.

- docs/kop.md
1. Refine the version variable
2. Add alias
> [docs] Update kop.md

- kafka-impl/pom.xml
- oauth-client/pom.xml
- pom.xml
- tests/pom.xml
Bump project version to 2.9.0-SNAPSHOT and pulsar dependency to 2.8.0.1.
> Bump version to 2.9.0-SNAPSHOT

- .github/workflows/pr-test.yml
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
This PR migrates https://github.com/streamnative/kop/pull/404 because it's too hard to cherry-pick them.
> [branch-2.7.2] Fix topic unload bug

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
- kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Fixes https://github.com/streamnative/kop/issues/619
See https://github.com/streamnative/kop/issues/619#issuecomment-886454987 for details.
> [branch-2.7.2] Fix unused getList call to create missed partitions

- tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
Fixes https://github.com/streamnative/kop/issues/650
`testPulsarProduceKafkaConsume` is flaky because the Pulsar producer may send messages asynchronously but is closed immediately.
Add a `CountdownLatch` to wait until all messages are sent successfully before the producer is closed.
> Fix flaky testPulsarProduceKafkaConsume

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/KafkaPrincipal.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/Session.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Resource.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/ResourceType.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/package-info.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java
#236 Add Authorizer used for authorization.
> [FEATURE] Add Authorizer used for authorization.

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
In previous code pass a ArrayList and change ArrayList in method may not a good idea. And we should follow the Kafka code with is:
```scala
def forEachTxnTopicPartition[B](f:(Int, BlockingQueue[TxnIdAndMarkerEntry]) => B): Unit =
markersPerTxnTopicPartition.foreach { case (partition, queue) =>
if (!queue.isEmpty) f(partition, queue)
}
```
Add a method `forEachTxnTopicPartition`.
> Refactor TxnMarkerQueue

- kafka-3-0/pom.xml
- kafka-3-0/src/main/java/io/streamnative/kafka/client/three/zero/Consumer300Impl.java
- kafka-3-0/src/main/java/io/streamnative/kafka/client/three/zero/Producer300Impl.java
- kafka-3-0/src/main/java/io/streamnative/kafka/client/three/zero/package-info.java
- kafka-client-api/src/main/java/io/streamnative/kafka/client/api/KafkaVersion.java
- kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactoryImpl.java
- pom.xml
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/saslplain/SaslPlainEndToEndTestBase.java
Modifications:
- add Kafka 3.0.0 clients
- run the tests against Kafka 3.0.0
> Add tests against Kafka 3 clients

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Code optimization: A large number of handle methods lack the @Override tag; there are a lot of warnings in the project in Idea:   Overridden methods are not annotated with '@Override'
> Code optimization: Overridden methods are not annotated with '@Override' 

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
When `GroupMetadataManager.shutdown()` the `scheduler` shutdown first, so there is no chance to execute `producer` and `reader` close.
Close `producer` and `reader` first.
> Fix producer and reader not close when GroupMetadataManager shutdown

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
Related to https://github.com/apache/pulsar/pull/10968
> [BUGFIX] Remove duplicated call skipBrokerEntryMetadataIfExist when parseMessageMetadata

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
> support max.message.bytes

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
- Improve handling of multiple loading of the same partition
- Remove useless debug variable 'loading' that didn't work with multiple partitions
> TransactionStateManager: improve loading mechanism

- README.md
- docs/upgrade.md
Fixes https://github.com/streamnative/kop/issues/879
Add a dependent document to describe the KoP upgrade issue. And fix the wrong links of README in main page. Remove all links for KoP < 2.8.0 and recommend users to use KoP >= 2.8.0
> [Docs] Add docs for KoP upgrade

- docs/configuration.md
Fixes https://github.com/streamnative/kop/issues/880
> [Docs] Add docs for mixed_kafka format

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
- pom.xml
Fix the spotbugs check like what https://github.com/streamnative/kop/pull/692 and https://github.com/streamnative/kop/pull/746 did.
> [branch-2.7.3] Bump Pulsar to 2.7.3.8-rc-3

- docs/configuration.md
Add missed docs for the feature of https://github.com/streamnative/kop/pull/943.
> Add docs about how to use KafkaPayloadProcessor

- docs/reference-metrics.md
> [Docs] add conversions time nanos docs

- docs/reference-metrics.md
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperation.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperationPurgatory.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
> Revert "Fetch: trigger pending fetches when producing messages. (#973)"

- README.md
Add wenbingshen into maintainer page. Thanks.
> add wenbingshen as maintainer

- kafka-0-10/pom.xml
- kafka-0-9/pom.xml
- kafka-1-0/pom.xml
- kafka-2-8/pom.xml
- kafka-3-0/pom.xml
- kafka-client-api/pom.xml
- kafka-client-factory/pom.xml
- kafka-impl/pom.xml
- kafka-payload-processor-shaded-tests/pom.xml
- kafka-payload-processor-shaded/pom.xml
- kafka-payload-processor/pom.xml
- oauth-client/pom.xml
- pom.xml
- test-listener/pom.xml
- tests/pom.xml
> Bump Pulsar to 2.10.0.1

- docs/implementation.md
The link to Bookkeeper documentation 404s.
Updated the link to the new address.
> Fixing linkrot in implementation.md

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Currently, when KoP handling finds transaction coordinator requests, it will store the group id. 
This is wrong behavior, the group id only stores when the consumer finds the group coordinator.
Do not store group id when handling find transaction coordinator requests.
> [Bugfix] Find transaction coordinator should not store group ID

- .github/workflows/pr-tests.yml
- codecov.yml
- pom.xml
Add code coverage report and upload to codecov.
> Add codecov report

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
Motivation:
The response map for a Produce Response corresponding to a Produce operation with non zero "timeout" is retained in memory for the whole timeout time. Under load this looks like a memory leak (it isn't really a leak but it add much pressure on the JVM).
Modification:
Move the lambda expression to a named class and explicitly release the references to the main data structures as soon as possible.
Results:
Even with basic testing with Pulsar Standlone and Kafka perf tools the improvements for the producer is visible.
Steps:
- start Standalone with the Kafka PH
- run the producer, at max speed 
`bin/kafka-producer-perf-test.sh --topic test --record-size 1024 --print-metrics  --throughput -1 --num-records 10000000 --producer.config config/producer.properties`
- run a consumer …
> [improvement] Release PartitionResponse data as soon as possible

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
Master Issue: #1599
See #1599 
The cause is that there is a variable that is captured by a deferred callback (TransactionMarkerRequestCompletionHandler).
Under heavy load you may have multiple instances of TransactionMarkerRequestCompletionHandler accessing the same List.
Do no re-use the variable
> [bugfix][transactions] TransactionMarkerChannelManager should not re-use the same variable

- kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
Fixes #944
See: https://github.com/streamnative/kop/issues/944#issuecomment-1158472965
The registered listeners would race with the future completion, which means there could be cases where the future has just completed and the already registered listeners are executing, and at the same time a new listener is registered, which causes a non-zero return value for `count()` which is smaller than previous `count()` return values.
Start a future and block it, register a few listeners, make sure they queue up, unblock the future, verify the registered listener methods are executed, and then register a new listener and check it doesn't block.
> Fix flaky-test: PendingTopicFuturesTest#testExceptionalComplete

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
> [branch-2.9.3][fix] Recycle fetchRequest records when resultFuture already complete

- README.md
- docs/configuration.md
- docs/kop.md
- docs/schema.md
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
Fixes https://github.com/streamnative/kop/issues/1673
> [docs] Add documents for KoP's Schema Registry

- pom.xml
JDK 17 compatibility when deploy to the nexus staging repository.
> Upgrade nexus staging maven plugin

- docs/security.md
The explanation how to configure OAuth2 wasn't accurate and a bit confusing
*(Please pick either of the following options)*
> Improve OAuth documentation

- pom.xml
Upgrade snakeyaml and jackson version
Extended integration test for recovery after broker failure*
> Upgrade snakeyaml and jackson version

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
add better log for CONCURRENT_TRANSACTIONS error
> [debug] add better log for CONCURRENT_TRANSACTIONS error

- tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopicTest.java
Fixes https://github.com/streamnative/kop/issues/1900
In this test, sometimes when `close` is called, the reader has already read the latest message. In addition, `readToLatest` might complete exceptionally because the reader might fail to read of get last message ID because it's closed.
- Add a `sleep` call in the callback argument of `readToLatest` to add the latency
- When the future of `readToLatest` failed, just checking `numMessageReceived` is less than `numMessages`.
> Fix flaky CompactedPartitionedTopicTest.testClose

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
Optimize getHeadersFromMetadata, replace Java streams with for loop
> Optimize getHeadersFromMetadata, replace Java streams with for loop

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PendingRequest.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
- kafka-impl/src/main/java/org/apache/kafka/common/requests/DataOutputStreamWritable.java
- kafka-impl/src/main/java/org/apache/kafka/common/requests/KopDataOutputStreamWritable.java
- kafka-impl/src/main/java/org/apache/kafka/common/requests/KopResponseUtils.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaCommonTestUtils.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Use ByteBuf for Request serialization
> [improvement] Use ByteBuf for Request serialization

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
Cherry pick https://github.com/datastax/starlight-for-kafka/commit/1a8b483457b187b11c3a1f9fd10669f06ece6050
and https://github.com/datastax/starlight-for-kafka/commit/8ab674550b18c95dfbd959853d744db780b1dbfa
Add logs
> [transactions] log when a TX Coordinator is still loading

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
(cherry picked from commit 7f59a829bfdfb5cffd7f4eda0dc8d549048c9e59) refer to https://github.com/datastax/starlight-for-kafka/commit/7f59a829bfdfb5cffd7f4eda0dc8d549048c9e59
Recover from failures during endTransaction after writing to storage.
Reset the transaction pending state from failures during endTransaction.  
> [transaction] Recover from failures during endTransaction after writing to storage

- kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
(cherry picked from commit 200f21a8383470042ba692b51b6eb1a2767b5a0b)
Save resources on the BK threads by not accessing the metrics context.
Record metric in the `sendResponseScheduler`.
> [improvement] Save resources on the BK threads by not accessing the metrics context

- kafka-0-10/pom.xml
- kafka-0-9/pom.xml
- kafka-1-0/pom.xml
- kafka-2-8/pom.xml
- kafka-3-0/pom.xml
- kafka-client-api/pom.xml
- kafka-client-factory/pom.xml
- kafka-impl/pom.xml
- kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/OffsetFinderTest.java
- kafka-payload-processor-shaded-tests/pom.xml
- kafka-payload-processor-shaded/pom.xml
- kafka-payload-processor/pom.xml
- oauth-client-shaded-test/pom.xml
- oauth-client-shaded/pom.xml
- oauth-client/pom.xml
- pom.xml
- schema-registry/pom.xml
- test-listener/pom.xml
- tests/pom.xml
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java
Update the Pulsar version to 3.1.1 and the project version to 3.2.0-SNAPSHOT.
> Update pulsar version and project version
