kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

Fix IllegalArgumentException for  KafkaConsumer#offsetsForTimes under kafka versions of 2.1.0 , 2.2.0 and 2.3.0

#135 fix IllegalArgumentException for  KafkaConsumer#offsetsForTimes

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java

Support listener either in format: type://:port, e.g.: "SSL://:9093", or in format: type://hostname:port, e.g.: "SSL://hostname:9093",
For the 1st format, need to fill it with advertisedAddress for hostname.
For the 2nd format, need to check the hostname is the same as advertisedAddress.

Support listener with no hostname, e.g. SSL://:9093

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java

In Pulsar standalone mode, If advertisedAddress not set, it is hard coded as "localhost":
```
if (this.getAdvertisedAddress() != null) {
// Use advertised address from command line
config.setAdvertisedAddress(this.getAdvertisedAddress());
zkServers = this.getAdvertisedAddress();
} else if (isBlank(config.getAdvertisedAddress())) {
// Use advertised address as local hostname
config.setAdvertisedAddress("localhost");
} else {
// Use advertised address from config file
}
```
And in KoP, if host address  not set in listeners, it will use advertised address to do the config.
Then the value read from conf.properties is outdated. This PR update it with right value.

fix advertised address config issue for standalone

---

integrations/python2-kafka-python/Dockerfile
integrations/python2-kafka-python/produceConsume.py
integrations/python2-pykafka/Dockerfile
integrations/python2-pykafka/produceConsume.py

In order to run kafka-python and pykafka lib on kop, we need a docker image which can run all versions of libs on it.
I generate kafka-python and pykafka docker image and the produce/consume examples.
@sijie @jiazhai  Please take a look, If it's ok, i will update #158 which depends on those docker images.

Generate kafka-python and pykafka docker image

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/timer/TimerTask.java

fix #181 
This pull request fix the deadlock in kop.

fix deadlock

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java

fix #186 
use `kafkaTenant` and `kafkaNamespace` set in broker.conf instead of `public` and `default` for `OffsetAcker ` when create consumer

use kafkaTenant and kafkaNamespace when OffsetAcker create consumer

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java

The `GroupCoordinator`'s startup method accepts a boolean param `enableMetadataExpiration`, which will be passed to `GroupMetadataManager#startup`. If it's true, the group metadata manager will clean up group metadata cache periodically.
However `enableMetadataExpiration` is false now. It should only be set false in tests.

Fix group coordinator's metadata never expired

---

.github/workflows/pr-test.yml

The DistributedClusterTest is hard to pass in CI tests environment, we disable it first to avoid CI failure.
The tracked issue: https://github.com/streamnative/kop/issues/184

Disable DistributedClusterTest

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java

related to https://github.com/streamnative/kop/issues/199, keep requestsQueue order using one thread to solve Correlation ID response in disorder.

keep requestsQueue order

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

kop data flow works like this:
kafka client(1) -> kop/broker (2)-> bookkeeper
Right now we can use throttler to slow down (2) data flood, but (1) doesn't have any protection. This pr is used to enable/disable auto read for (1) channel. With this, we can controll the speed of channel in case of potential oom issue.

add back press for kop server

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java

KafkaHeaderAndRequest contains native memory references. When getting a lot of requests from kafka client, for example 10 million per seconds, those redundance references will stop gc collection and memory get increased.
It would be tricky to provide unit test for this patch and this pr seems to be a minor change, so I didn't write test case for it.

remove redundance reference to get rid of native memory leak when getting a lot of requests.

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestTypeTest.java

to solve https://github.com/streamnative/kop/issues/226, and this patch can improve producing performance about 5 times.

use producer to publish message for metrics collected by pulsar

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/package-info.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTest.java

Fixes #208 
This PR ports Kafka's `SaslServerAuthenticator` into KoP with some limits:
- Don't handle authentication corner cases for the Kafka Client 0.9.0.x, it's too troublesome and KoP doesn't support Kafka Client 0.9.0.x now.
-  Don't handle `SaslHandshakeRequest` v0 because this request has no header that it takes a lot of efforts to refactor current code and test.
- Keep the old authentication way, i.e. user pass a `username` field to represent the namespace and a `data` field to represent the token, then Pulsar broker will use JWT authentication to do the actual authentication. See `docs/security.md` for details.
- Add a unit test to cover the case that client doesn't configure authentication.
More works to do:
- Currently it just does a simple check for permissions in the …

Perform authentication before processing other requests

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

KoP needs no controller id because it's used for metadata operations in Kafka. So it simply sets controller id field to -1 when metadata request is processed.
However, before a Kafka's `AdminClient` send a metadata related request like `CreateTopics`, it sent a metadata request and try to get a valid controller broker from the controller id field of metadata response. If the controller id is invalid, the `AdminClient` will send metadata request infinitely.
Since each broker can manage metadata, this PR change metadata response's controller id to the self node's controller id, which is generated by a hash function.
In addition, this PR adds a test to verify Kafka's `AdminClient` won't stuck at the `CreateTopics` method which is not supported currently.

Set controller to broker itself when metadata request is processed

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Fixes [#230](https://github.com/streamnative/kop/issues/230)
The offset field is not filled when a PRODUCE request is processed yet. It causes that the offset what Kafka producer get from `send()`'s callback is always -1, which may cause some problems like [#241](https://github.com/streamnative/kop/issues/241) mentioned.
This PR fills the offset field and add a unit test to verify if the right offset is set.

Fill the offset field of PartitionResponse

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedCreateTopics.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Master issue: #241 
This PR add support for Kafka `CreateTopics` request so that topics can be created by Kafka's `AdminClient`. Related tests are added to verify 
The `validateOnly` field introduced from `CreateTopics` request v1 is not processed. The `validateOnly` field only checks the topics can be created as specified but not creates anything. It's not a important feature currently so leave it as a future task.

Support CreateTopics request

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/KopTopicTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTest.java

Master issue: [#241](https://github.com/streamnative/kop/issues/241) 
Currently if a Kafka Client tries to list all topics, the topic name in response will contain the namespace prefix like "persistent://public/default". However, for topics in the default namespace, they shouldn't contain the prefix because Kafka Client would like to use the short topic name. So this PR will remove the prefix of topics in the default namespace.

Remove namespace prefix for topics in the default namespace

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduce.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduceQueue.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTest.java

Fixes [#247](https://github.com/streamnative/kop/issues/247)
The original implementation of message publishing cannot guarantee that a topic partition's pending writes are completed in order. This PR is to fix the issue by refactoring the handler for Produce requests.
The basic steps of handling a single partition's produce request are:
1. Get `PersistentTopic` from topic manager;
2. Convert Kafka's `MemoryRecords` to Pulsar's `ByteBuf`;
3. Call `PersistentTopic#publishMessages` to write `ByteBuf` to BK asynchronously.
This PR adds a `PendingProduce` class to compose pending step 1 and 2 to a `CompletableFuture`, then add the `PendingProduce` object to a queue (`PendingProduceQueue`) which is associated with the partition name in a map named `pendingProduceQueueMap`. When the step 1 and 2 …

Fix message disorder

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaLogConfig.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Master issue: [#241](https://github.com/streamnative/kop/issues/241) 
This PR add support for Kafka `DescribeConfigs` request. The request is to get topic or broker related configs from Kafka but the Kafka's config is much different from KoP. We just only support request for topic's configs and use the default config value so that Confluent Schema Registry can run with KoP.

Support DescribeConfigs request

---

tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java

This PR add a unit test to verify that when KoP is running with Confluent Schema Registry, Kafka Client with `KafkaAvroSerializer` or `KafkaAvroDeserializer` works well with different message types. The timeout is a little longer than other tests because it takes some time to start the schema registry service.

Add tests to verify KoP with Confluent Schema Registry

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java

fixes #220
if using `computeIfAbsent `, `consumerManagerFuture.complete(null)` will store in `consumerTopicManagers`, and `getTopicConsumerManager ` will always get future null cache for key which should getTopic again.

remove null future cache from consumerTopicManagers

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Fixes [#273](https://github.com/streamnative/kop/issues/273)
When KoP handles metadata requests, it only checks the config `allowAutoTopicCreation` but not the same field in the metadata request. Then it causes that `AdminClient#describeTopics` returns a success result even if the topics don't exist and topics will be created automatically.
So this PR adds the check for metadata request's `allowAutoTopicCreation` field and the test for `AdminClient#describeTopics`.

Fix topic auto created when using Kafka AdminClient to get metadata

---

kafka-impl/pom.xml
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaBrokerStarter.java
pom.xml
tests/pom.xml

Bump pulsar to 2.7.0. Since BookKeeper API has changed, the KoP will be incompatible with Pulsar 2.6.x after this PR.

Bump pulsar to 2.7.0

---

kafka-impl/pom.xml
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
pom.xml
tests/pom.xml

This PR bumps project version to 2.8.0-SNAPSHOT. Also it bumps pulsar version to 2.8.0-rc-202012200040 so that we can make use of some latest features.

Bump version to 2.8.0-SNAPSHOT

---

kafka-impl/conf/kop.conf
kafka-impl/conf/kop_standalone.conf
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterFactory.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatterHeader.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EncodePerformanceTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/NoHeaderKafkaEntryFormatter.java
kafka-impl/src/test/resources/log4j2.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaSSLChannelTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaSSLChannelWithClientAuthTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottleTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/GlobalKTableTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KafkaStreamsTestBase.java

It's a follow PR of [#280](https://github.com/streamnative/kop/pull/280). This PR adds an optional value to `entry.format` config so that user can improve the performance because there's little entry conversion between `MemoryRecords` and entry's `ByteBuf`, while the cost is that Kafka client won't be compatible with Pulsar client.
Because the entry format of `kafka` still adds a `MessageMetadata` header to record the `entry.format`, it will be possible for Pulsar broker/client to decode these messages later.
This PR adds a `KafkaEntryFormatter` class associated to `entry.format=kafka` and apply this config to existed tests that have relation to Kafka client but not Pulsar client. An exception is `SaslPlainTest`, it will fail when multiple test instances are created because `LOOKUP_CACHE` …

Add KafkaEntryFormatter

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduce.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaProducerStatsTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestTypeTest.java

fixes #284
pulsar will add a `updateRates` method for this PR.

collect publish rate

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java

fixes #266 
`topics` in `KafkaTopicManager` will cache `PersistentTopic` by `brokerService.getTopic`, it's unnecessary because `PersistentTopic` is cached in `brokerService.getTopic`. we should remove it to avoid getting a `null` topic.

remove unnecessary topics cache for Topic Manager

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java

Fixes #299 
`PulsarEntryFormatter` doesn't handle null value correctly now. If a message with null value was sent by a producer, the consumer will receive a message with an empty string.
This PR fixes the bug and adds to tests to verify KoP could handle the null value no matter what the entry format is.

Fix PulsarEntryFormatter not handle null value correctly

---

README.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduce.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatterHeader.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetSearchPredicate.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CommitOffsetBacklogTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledPulsarTest.java

Fix #290 
This PR supports continuous offset for kop.
Since this PR disable the orginal design of mapping between Pulsar `MessageId` and Kafka `offset`. So I just ignore some UnitTest based on the original desing. 
Maybe we can raise up another issue to track how we deal with these ignored tests.

Support continuous offset for kop

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

When `KafkaConsumer` send OffsetCommitRequest,
the field `retentionTime` is always set to -1,
and kafka server convert the retentionTime according to server config.
this patch add convert logic the same as kafka server
to avoid kop expire the wrong commit offset in
`GroupMetadataManager.cleanupGroupMetadata` logic.
test in `KafkaRequestHandlerTest.testOffsetCommitRequestRetentionMs`

[Issue #303] handle OffsetCommitRequest retentionTime field convert properly

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/EndPointTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Fixes #315 
The original `listeners` config's semantics is wrong that it mixed the `listeners` and `advertised.listeners` semantics of Kafka. So this PR adds a `kafkaAdvertisedListeners` as the listeners exposed to client, and only use `listeners` as the bind address. To avoid conflict with other protocol handlers, mark `listeners` as deprecated and use `kafkaListeners` instead.
For convenience, this PR adds an `EndPoint` class to do the listener url parse work, which can be applied to both `kafkaListeners` and `kafkaAdvertisedListeners`. It also handles `SASL_XXX` protocols which were not handled before. And the related tests are added.
The existed `KafkaApisTest#testBrokerHandleTopicMetadataRequest` could verify the `kafkaAdvertisedListeners` because the tests' …

Add advertised listeners as the listeners exposed to client

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

If `kafkaAdvertisedListeners` that was introduced from #317 was not set, the KoP would fail to start. It's because in `KafkaProtocolHandler#start` we use `kafkaConfig.getKafkaAdvertisedListeners()` to get the configured `kafkaAdvertisedListeners` which is null. But we need to call `KafkaProtocolHandler#getKafkaAdvertisedListeners` to get the `kafkaListeners`/`listeners` if `kafkaAdvertisedListeners` is null.
This PR overwrites the `KafkaServiceConfiguration#getKafkaAdvertisedListeners` to fix this issue.
This issue was not exposed because the `kafkaAdvertisedListeners` has been set in `KopProtocolHandlerTestBase#resetConfig` before. So this PR removes the default config and only set it in `KafkaApisTest` for verification of the `kafkaAdvertisedListeners`.

Fix NPE if kafkaAdvertisedListeners was not set

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java

simplify `MessageIdUtils.peekOffsetFromEntry` by use `Commands.peekBrokerEntryMetadataIfExist` directly

simplify peekOffsetFromEntry

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespacePulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTestBase.java

The cherry picks of #267 exposed the potential problem that is mentioned in #293 , this PR is to fix the broken branch-2.7.0

Fix test failures

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

This PR is a partial fix of https://github.com/streamnative/kop/issues/332.
Before this PR, the `MessagePublishContext` completed with the current offset, which is the latest offset. Then `PartitionResponse` will be filled with the offset. However, Kafka producer treat the `PartitionResponse`'s offset as the base offset.
For example, before this PR, when Kafka producer sends a batch with 3 single messages to a new topic, the offsets in send callback will be `(2, 3, 4)` before this PR. After this PR, the offsets in send callback will be `(0, 1, 2)`.

Fix wrong offset in send callback

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

fix #334 
This PR fix listOffset returns wrong value

fix listOffset returns wrong value

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

revert https://github.com/streamnative/kop/commit/9a4be2112dfd0cb7c0dbbc3c506ca083506310bd, fixes #355

revert 9a4be21 for close configuring channel auto-read

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java

For `DefaultOffsetsTopicNumPartitions` in code is set to `1`, however the document setting is `8` . `DefaultOffsetsTopicNumPartitions` should be greater than `1` to improve the throughput.
1. Sync with documentation and set to `8`

change default offsets topic number partitions to 8

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetFinder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetSearchPredicate.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/OffsetFinderTest.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimePulsarFormatTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Fixes https://github.com/streamnative/kop/issues/336
Besides applying the LightProto generated new package name and some new APIs, this PR also fixes the tests error caused by https://github.com/apache/pulsar/pull/9240, which introduces a new method `PulsarService#createLocalMetadataStore`.
And some tests are affected by the wrong parse of entry data after the pulsar update, this PR fixes the test failures.

Upgrade pulsar with LightProto support

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

support delete topics using the kafka client

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java

fixes #353
1, `responseData` is `LinkedHashMap`, which implementation is not synchronized, therefore `responseValues` should not parallel.
2, `getExecutor schedule` may not process so fast for lots of partitions.

fix can not consume all message if topics has > 1000 partitions

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

The `testCreateInvalidTopics` sometimes failed in CI environment, like
```
Error:  testCreateInvalidTopics(io.streamnative.pulsar.handlers.kop.KafkaRequestHandlerTest)  Time elapsed: 5.022 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at io.streamnative.pulsar.handlers.kop.KafkaRequestHandlerTest.testCreateInvalidTopics(KafkaRequestHandlerTest.java:359)
```
However here we only use `assertTrue` to check the cause type of the `ExecutionException` but not printed it. So this PR adds error logs for debugging.
Normally it should returns a `TimeoutException`. However, the …

Fix flaky testCreateInvalidTopics

---

pom.xml

Currently the CI kop integration tests may fail with
> Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: quay.io/testcontainers/ryuk:0.2.3"}
It may be caused by the `test containers`'s too old. This PR tries to fix the problem.

Upgrade testcontainers to 1.15.1

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java

1. remove log if the active transaction map is empty.
2. return the `highWaterMark` if there is no active transaction.

Clean log and return highWaterMark if active transactions not exist

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerTest.java

Complete the ProducerIdManager component and add tests for it.

Complete the ProducerIdManager component

---

kafka-impl/pom.xml
pom.xml
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CommitOffsetBacklogTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

Besides bumping pulsar version, this PR also fixes the compile error caused by new `PersistentTopic#getStats` API.

Bump pulsar to 2.7.0.8-rc-202102191415

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java

This pull request fixes a group state transition problem when running group rebalance. When we constantly start and stop a consumer task to consume a topic using the same groupid, we found that our client program may occasionally hold for about 30 seconds and then receive a log
```
Group coordinator XXX (id: YYY rack: null) is unavailable or invalid, will attempt rediscovery
```
After that, the client program returns to normal.
```java
// GroupCoordinator.java
private void removeMemberAndUpdateGroup(GroupMetadata group,
MemberMetadata member) {
group.remove(member.memberId());
switch (group.currentState()) {
case Dead:
case Empty:
break;
case Stable:
case CompletingRebalance:
maybePrepareRebalance(group);
break;
case PreparingRebalance:
// …
```

[BUGFIX] join operation could not be finished and proceed group rebalance

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaService.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CommitOffsetBacklogTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

This version update is convenient for tests in real environment since there's no binary download url for original pulsar `2.8.0-rc-202101252233`.
This PR fixes the API incompatibility problems that are introduced by https://github.com/apache/pulsar/pull/9397 and https://github.com/apache/pulsar/pull/9302.
Another significant change between these two versions is https://github.com/apache/pulsar/pull/9338, which introduced metadata-store API for cluster resources. This PR fixed the test failure caused by it as well. Since KoP `tests` module only uses one `MockZooKeeper` to manage z-nodes, see `KopProtocolHandlerTestBase#createMockZooKeeper`, the mocked `createConfigurationMetadataStore` method returns `mockedZooKeeper` here instead of a `mockedZooKeeperGlobal` like what Pulsar did in …

Bump pulsar to 2.8.0-rc-202102252222

---

pom.xml

KOP put pulsar dependency jar into nar package, which lead the nar size up to 130MB. However, the kop nar run with pulsar broker, the pulsar dependency is no need to be packed into KOP nar package.
1. change pulsar dependency jar scope to provided in pom.xml

change pulsar dependency jars to provided scope to reduce nar package size

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java

The decode method in `KafkaEntryFormatter` is time-consuming among which the process of constructing `MemoryRecordsBuilder` takes the highest proportion of time. 
Therefore our aims are:
1. overwrites `BaseOffset` field in byte buffer directly to avoid time-consuming iteration which is mainly used for assigning offsets
2. concatenates multiple record batches into one `MemoryRecords` object to better simulate kafka's behavior
- remove the iteration of continuously appending records in the `MemoryRecordsBuilder`
- change to one-to-one correspondence between batch and entry

[ENHANCEMENT] perf tuning in decode phrase

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

KOP receives Kafka messages produced by all kinds of Kafka Producer, and packed into pulsar entry and stored in bookkeeper without validation. If Kafka producer produced a broker message to KOP, the consumer will parse failed and may cause consumer failed.
1. Add message validation in KOP `handleProduce` stage. If it validate failed, return error to Kafka Producer and request resend to ensure valid message stored in bookkeeper.

add produce message validation

---

oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthLoginCallbackHandler.java

When Kafka client uses KoP's `OauthLoginCallbackHandler` as its `sasl.login.callback.handler.class` config, the client cannot exit normally even after client is closed. It's caused by unclosed `Authentication` instance.

Fix leak of login callback handler

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java

Fixes https://github.com/streamnative/kop/issues/229
The consumers of `OffsetAcker` are used to commit offsets only. However, they would never be closed. Therefore the topics that are consumed by Kafka clients cannot be deleted because topic has active producers/subscriptions.
- Record all group IDs before group coordinator handles `SYNC_GROUP` request, which will call `OffsetAcker#addOffsetsTracker` to add offset consumers if success.
- Close and remove the consumers associated with the recorded group IDs before during the close phase of channel. It's okay because `OffsetAcker#getConsumer` (called by `ackOffsets`) will recreate the consumer if it doesn't exist.
- Add tests to delete a topic after all Kafka clients are closed.

Close offset consumers when channel is inactive

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionLogKey.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionLogValue.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionState.java

Transaction log key and value are the preconditions of the transaction log.
The transaction log key will be encoded to bytes and set in message key bytes.
The transaction log value will be encoded to bytes and set in message value bytes.

[Transaction] Add transaction log key and transaction log value

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerTest.java

Add initialize transaction metadata.
Transaction metadata initialization is the precondition of the transaction log. Transaction metadata base topic name `${KafkaMetadataTenant}/${KafkaMetadataNamespace}/__transaction_state`.
The metadata topic partition could be set by the configuration `txnLogTopicNumPartitions` of the KoP configuration.

[Transaction] Add initialize transaction metadata

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java

`testDeleteClosedTopics` is very easy to fail in CI environment because there's a race condition. https://github.com/streamnative/kop/pull/425 closes a group's offset consumers when the channel becomes inactive. However, before Kafka consumer closes, it sends a `COMMIT_OFFSET` request to commit offsets, which is the behavior of the default `enable.auto.commit=true` config. Currently, KoP acknowledges the offset's associated message id in the callback of `GroupMetadataManager#storeGroup`, see `GroupCoordinator#handleCommitOffsets`:
```java
result.whenCompleteAsync((ignore, e) ->{
if (e == null){
offsetAcker.ackOffsets(groupId, offsetMetadata);
}
});
```
So it's asynchronous with `handleCommitOffsets` itself. There's a possibility that after the channel was closed and `OffsetAcker`'s …

Fix flaky testDeleteClosedTopics

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java

Sometimes multiple brokers could subscribe the same topic partition and fail with `ConsumerBusyException`:
```
WARN  io.streamnative.pulsar.handlers.kop.coordinator.group.OffsetAcker - Error when get consumer for offset ack:
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
```
This problem was mentioned in https://github.com/streamnative/kop/pull/263 before. However, switching the subscription type to shared or failover is not correct because a partition should have only one consumer at the same time. The problem is before updating consumer metrics, it uses `OffsetAcker#getConsumer` to check if the consumer has been created. This check is wrong.
Firstly, `OffsetAcker#getConsumer` may …

Avoid creating offset consumer before updating consumer metrics

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

Fixes #322 
The `DelayedOperationPurgatory` field of `AdminManager` will never be closed, so the `ShutdownableThread` would be started each time a request handler is created and won't be stopped.

Fix AdminManager memory leak

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

Fixes #322
The `DelayedOperationPurgatory` field of `AdminManager` will never be closed, so the `ShutdownableThread` would be started each time a request handler is created and won't be stopped.

Fix AdminManager memory leak (#438)

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

This PR introduces 3 metrics that are related to requests.
- REQUEST_QUEUE_SIZE: the size of `requestQueue` in `KafkaCommandDecoder`.
- REQUEST_QUEUED_LATENCY: the latency between a request enqueues to `requestQueue` and the request is dequeued.
- REQUEST_PARSE: the time to parse a raw request

Add request related metrics

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

This case is usually encountered when attempting to use KoP with
standalone mode. When new behavior was introduced in #168 standalone
mode was broken due to sample namespace setup etc not taking place until
after the broker is initalised (which in turn initialises protocol
handlers).
Fixes #185

Create cluster if it doesn't exist during metadata initialisation

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduce.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java

Fixes #332 
The offset in produce callback may be not accurate when the messages are sent in batch, see https://github.com/streamnative/kop/issues/332#issuecomment-762712235 for detail explanation.
Since https://github.com/apache/pulsar/pull/9257 introduced a new API that supports fetching some metadata from the entry data, we can use this API to get the accurate offset.

Use setMetadataFromEntryData API to retrieve offset

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
pom.xml

Bump pulsar to 2.8.0-rc-202104202206 and fix the incompatible interface.

Bump pulsar to 2.8.0-rc-202104202206

---

.github/workflows/pr-tests.yml
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Fix #252 
When bundle unload triggered, the `consumerTopicManagers` cache won't be evicted and it will return the old `KafkaTopicConsumerManager` instance in the next fetch request handle. However, after bundle unload, the producer/consumer/managedLedger of topics in related bundle will be closed. If we use old  `KafkaTopicConsumerManager` instance to read messages, it will return `managedLedger has been closed` exception.
1. Change `consumerTopicManagers`, `topics`, `references` map to static attribute ConcurrentHashMap.
2. Evict related cache information for topics whose bundle trigged unload.
3. Turn on `DistributedClusterTest `.

fix issue #252 bundle unload bug

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/org/apache/kafka/common/requests/ResponseCallback.java
kafka-impl/src/main/java/org/apache/kafka/common/requests/ResponseCallbackWrapper.java

Keep the data in the direct memory of nio as much as possible to reduce the damage to performance.
1. modify `ByteBuf` directly instead of `MemoryRecords`
2. delay the release timing of `Entry` until after writing to the network channel

[ENHANCEMENT] memory tuning for decode phrase

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java

We need to add message ttl for kafka metadata namespace.
1. add message ttl configuration for kafka metadata namespace.

add message ttl for kafka metadata namespace

---

docs/configuration.md

1. In order to sync with code default value, update kafka metadata namespace retention from 7 days to 3 days in configuration doc.

update kafka metadata namespace retention doc

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduce.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java

For inner topic, such as, __consumer_offsets, __transaction_stats, and system topic, such as, __change_event, they are expose to all users and can produce / consumer message to / from those topic, which will cause the cluster crash.
1. add produce protection for inner topic on KOP side.
TODO
1. for consume protection, it's in testing.

Add inner topic protection

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/FakeArrayBlockingQueue.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/FakeArrayBlockingQueueTest.java

https://github.com/streamnative/kop/pull/429 added the `maxQueuedRequests` to limit the number of pending requests for each channel. However, the elements of `requestQueue` are never used. In Kafka the request that is polled from `requestQueue` will be passed to `KafkaApis` to handle. However, KoP use Netty's `channelRead` to handle each request.
- Add a `FakeArrayBlockingQueue` class whose implementation is ported from `ArrayBlockingQueue`. The difference is that it never stores any element.
- Add unit tests for `FakeArrayBlockingQueue`.
- Change `requestQueue`'s type to `FakeArrayBlockingQueue`.
- Do some code refactors for `requestQueue` and `responseQueue` to avoid unnecessary null checks.

Don't save KafkaHeaderAndRequest in a real queue

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingProduce.java

Use an `AtomicBoolean` as `KafkaTopicManager`'s state to avoid using a normal boolean and read write lock.
In addition, add the state check for some non-static methods as well as some minor refactors.

Use AtomicBoolean as KafkaTopicManager's state

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java

Motivation: Remove CompositeBytebuf to avoid on-heap memory copy in `KafkaEntryFormatter#decode`
Related to: #447

[ENHANCEMENT] Remove CompositeBytebuf to avoid on-heap memory copy

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Fix flaky tests of branch-2.7.1, which includes:
- KafkaRequestHandlerTest#testProduceCallback
- BasicEndToEndPulsarTest#testNullValueMessages

Fix flaky tests of branch-2.7.1

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java

https://github.com/streamnative/kop/pull/429 introduced a request timeout to avoid some requests being blocked by the previous requests. However, it changes the behavior of `writeAndFlushResponseToClient`.
Before #429, `writeAndFlushResponseToClient` removed all completed response futures in the head of `responseQueue` and then sent the completed response to client.
After #429, `writeAndFlushResponseToClient` removed all response futures, and use `CompletableFuture#get(long timeout, TimeUnit unit)` to wait until all futures are completed or expired.
We shouldn't wait any `CompletableFuture` in a `CompletableFuture`'s callback.
In `writeAndFlushResponseToClient`, only remove completed **or expired** response futures. Here we combine `peek` and `boolean remove(Object o)` for thread safety. …

Refactor writeAndFlushResponseToClient

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

Many usages of `KafkaTopicManager#getTopic` are wrong because they didn't check null value so that NPE may happen. And the semantics of `KafkaTopicManager#getTopic` is wrong because the `createIfMissing` argument of `BrokerService#getTopic` is true, so if a not existed topic's name was accepted as the argument, the topic would be created automatically. This behavior is unexpected because we only want to create topics automatically in `METADATA` request handler.
1. In `KafkaTopicManager#getTopic`, when `BrokerService#getTopic` is completed exceptionally, returns an exceptionally completed future instead of a null completed future.
2. Use `whenComplete` for all `getTopic` references so that we can handle null completed futures and exceptionally completed futures.
3. The `LIST_OFFSET` …

Fix wrong semantics and usage of KafkaTopicManager#getTopic

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottleTestBase.java

This PR upgrades pulsar dependency to 2.8.0-rc-202105092228, which has two major API changes.
https://github.com/apache/pulsar/pull/10391 changed `LoadManager` API so that `MetadataCache` is used instead of `ZookeeperCache` in this PR.
https://github.com/apache/pulsar/pull/7406 changed the throttling strategy. However, currently KoP is different from Pulsar that the produce and its callback may be in different threads. KoP calls `PersistentTopic#publishMessages` in a callback of `KafkaTopicManager#getTopic` if the returned future is not completed immediately. Otherwise, it's called just in the I/O thread. Therefore, here we still use a **channel based** publish bytes stats for throttling, while https://github.com/apache/pulsar/pull/7406 uses a **thread based** publish bytes stats.
The …

Fix publish throttling and LoadManager API for pulsar upgrade

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

Fixes https://github.com/streamnative/kop/issues/493
This bug was introduced by https://github.com/streamnative/kop/pull/473. In `MessageFetchContext#handleFetch`, when the `KafkaTopicConsumerManager`'s future is completed with null, we should remove the future from `KafkaTopicManager#consumerTopicManagers`.
In addition, this PR adds some refactors for `consumerTopicManagers`:
1. Don't use getter to expose this field, use methods to operate it instead.
2. Check null for completed future before close `KafkaTopicConsumerManager`.

Fix null KafkaTopicConsumerManager not removed

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedProduceAndFetch.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperationKey.java

KoP uses `requestTimeoutMs` config to prevent asynchronous `responseFuture` timeout, but `FetchRequest` and `ProduceRequest` have it's own timeout parameters which are brought in from the client, we should replace the default request timeout for `Produce` and `Fetch`.

add produce/fetch timeout

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/FakeArrayBlockingQueue.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

Some request queue size metric doesn't use correct metric type.
1. Fix request queue size metric type
2. Add response queue metric to leverage whether keep order operation cost too much time.

Fix request queue size metric and add response queue metrics

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

Sometimes `DifferentNamespaceTest` may fail, after checking the logs I found send failed.
> Failed to send 0: This server is not the leader for that topic-partition
Kafka 2.0 client's default `retry` config is 0, so it won't attempt to send message again.
It's because when KoP handled PRODUCE request, the `PersistentTopic` instance of broker was not created. It's because when a topic was automatically created, an asynchronous method was called but METADATA response future didn't wait for it. The followed lookup request doesn't need a topic to be created.
When a METADATA request is handled and a topic is created automatically, wait until the topic creation is completed.

Fix topic creation may not complete after METADATA response is sent

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java

When running kop and entered api operation completed and timeout, it will throw the following exception.
```
21:04:37.951 [pulsar-io-20-4:io.netty.util.concurrent.AbstractEventExecutor@166] WARN  io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: io.streamnative.pulsar.handlers.kop.Kafka
CommandDecoder$$Lambda$893/1938241875@7b666c80
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138) ~[netty-common-4.1.63.Final.jar:4.1.63.Final]
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByt …
```

fix bytebuf release bug

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatter.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

In order to expose consumer stats, KOP create a consumer and update the stats metric to consumer object.  
It's too expensive.
1. expose consumer stats to prometheus instead of consumer internal stats
1. groupid still should store in zookeeper, it's hard to remove.

expose consumer stats to prometheus instead of consumer internal stats

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Upgrade pulsar dependency to a newer version (2.8.0-rc-202105182205) that contains https://github.com/apache/pulsar/pull/10601, which corrected the wrong semantics of `getPartitionedTopicMetadataAsync` that returns 0 for a non-existed topic.

Apply getPartitionedTopicMetadata API with correct semantics

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java

1. Add system topic protection for handleProduce. However, there is a bug in pulsar, i will fix it by another PR on Pulsar.
2. Fix a bug in `InnerTopicProtectionTest`. 
I turn off the system topic produce test in `InnerTopicProtectionTest` first, after fixed on Pulsar side for system topic check, and KOP merged the Pulsar master, i will turn on again.

fix inner topic protection bug

---

docs/kop.yaml
pom.xml

1. upgrade pulsar dependency to include the following bug fix
- https://github.com/apache/pulsar/pull/10706 : fix load __consumer_offset topic timeout on bundle onLoad stage
- https://github.com/apache/pulsar/pull/10341 :  fix create reader failed on bundle onLoad stage

upgrade pulsar dependency to 2.8.0-rc-202105291235

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

When a consumer sends FETCH requests frequently, for example, polling in a tight loop,
```java
while (true) {
ConsumerRecords<String, byte[]> records = consumer.poll(Duration.ofMillis(100));
// process records quickly
}
```
the heap memory increasing quickly and GC will happen frequently about once per minute. The frequency is not related to the throughput but the count of FETCH requests.
It's because each time a FETCH request arrived, KoP will create a `MessageFetchContext`. Though it's allocated in a Netty recycler, there're a lot of small objects that are still allocated from heap memory. There're a lot of wait all operations, for example, after all `PersistentTopic`s of each partition were get, it collected all those `PersistentTopic`s to a list and retrieve partition's associated …

Refactor FETCH request handler to reduce GC

---

docs/reference-metrics.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

1. fix request_queue_size guage stats bug
2. add `ALIVE_CHANNEL_COUNT` and `ACTIVE_CHANNEL_COUNT` gauge stats
3. add labels for request queued latency

add labels for request queued latency and fix request queue size bug

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ZooKeeperUtils.java

Currently KoP writes group name and the associated client's host and id to ZK so that consumer stats could be updated while FETCH request contains no group info. However, there is something wrong with ZooKeeperUtils.
First, when the `groupIdStoredPath` already existed, the write to ZK may fail with `NodeExists` because of race condition.
Second, if the data was failed to be written to ZK, every time a FETCH request comes, a ZK read operation will be performed. It's because `ZooKeeperUtils#getData` returns null if the node doesn't exist and a null value cannot be put into a `Map`. In this case, `ConcurrentHashMap#computeIfAbsent` will always execute the second argument to create a value.
- Create groupIdZooKeeperPath only when KoP starts, and only log the error message if ZK write failed. …

Handle group name was failed to be written to ZK gracefully

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

Fixes https://github.com/streamnative/kop/issues/544
After the debugging, when a FETCH request contains many partitions, for each partition, `KafkaTopicConsumerManager#remove` will be executed in the same `pulsar-io-<suffix>` thread, which will eventually call `MessageIdUtils#getPositionForOffset` to get `PositionImpl` of the offset.
However, `getPositionForOffset` is a synchronous method that waits until a `CompletableFuture` is done. The future is returned by `ManagedLedgerImpl#asyncFindPosition` that calls `ManagedLedgerImpl#asyncReadEntry` internally. If the producer is publishing messages at the same time, the `asyncAddEntry` method could be called for the same `ManagedLedgerImpl` object. It will somehow cause the deadlock.
- Just use `ManagedLedgerImpl#asyncFindPosition` instead of …

Fix deadlock caused by synchronous asyncFindPosition

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java

Currently some configurations are not listed in docs. This PR adds these configurations and split them to different sections. BTW, fix the inconsistency between docs and code for `maxReadEntriesNum`. This PR also makes the partitions of metadata topics consistent with Kafka's config.

Update documents for configuration

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/exceptions/KoPBaseException.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/exceptions/KoPMessageMetadataNotFoundException.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/exceptions/package-info.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetResetTest.java

Fix #442 
1. Add NPE check for `peekOffsetFromEntry` and `peekBaseOffsetFromEntry`
2. Auto skip fetched exception entry in decode stage to avoid direct memory leak.

fix direct memory leak bug

---

docs/security.md

Currently the docs related to SSL keys is not friendly to users that are not familiar with `keytool` and `openssl` commands. For some commands we need to specify the password, while for some other commands we need to input the password we have specified before.
In addition, this PR removes the redundant blanks of the line tail.

[Docs] Add more details for SSL keys

---

.github/workflows/pr-impl-test.yml
.github/workflows/pr-integration-tests.yml
.github/workflows/pr-tests.yml

Currently CI tests are disabled for branch-2.8, see https://github.com/streamnative/kop/pull/576. This PR enables CI tests for PRs that are merged to `branch-*`.

Enable CI tests for branch name start with 'branch-'

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
pom.xml

Pulsar 2.8.0.3 removed the dependency for freebuilder. From `mvn dependency:tree` command, it was imported by `org.apache.bookkeeper:stream-storage-java-client:jar:4.14.1` before. This PR fixed the KoP build for Pulsar 2.8.0.3.

Remove dependency for freebuilder

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

Fixes #591 
Kafka Connect use `Admin#createTopics` and check the `TopicExistsException` exception for existed topics. See https://github.com/apache/kafka/blob/ef3cd68c852daf21d8e207fa8e21c8770f4041d7/connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java#L394 for details.
However, currently `Admin#createTopics` will return an `UnknownServerException` for any failure when create topics. In addition, the handler for CreateTopics request has other problems.
1. The default partition number (-1) is not handled, which may throw exception from `createPartitionedTopicAsync`.
2. If topic name is invalid, the future won't be completed until timeout. See https://github.com/streamnative/kop/pull/361, TimeoutException will be thrown in this case.
1. When the topic to create …

Fix some corner cases not handled well for CreateTopics request

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTestBase.java

Currently KoP  only creates the namespace for kafka metadata defined by `kafkaMetadataTenant` and `kafkaMetadataNamespace` when started, but not create the namespaces for kafka topics defined by `kafkaTenant` and `kafkaNamespace`.
This pull requeset add the initialization of namespaces for kafka topic.

create kafka namespace if missing

---

docs/kop.md

When KoP is auto released by streamnative-bot, the `{{protocol:version}}` will be replaced to the actual version so that https://hub.streamnative.io/protocol-handlers/kop/0.2.0 can grab the content.

Update download link to synchronizing content to StreamNative hub

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ZooKeeperUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

Fixes #606 
If a consumer from the same machine subscribed the same topic with a different group id, the `FIND_COORDINATOR` request handler would fail to update the z-node for consumer metrics.
In another case, if a consumer from the same machine subscribed the same topic with the same group id again, the KoP side would print redundant error logs like #606.
- If the z-node existed in `ZooKeeperUtils#tryCreatePath`, update the z-node's data instead of just printing an error log.
- Add a unit test to verify group id can be updated successfully.

Fix group id z-node not updated for the same client id

---

kafka-1-0/pom.xml
kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ConsumerImpl.java
kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ProducerImpl.java
kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/package-info.java
kafka-client-api/pom.xml
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Consumer.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ConsumerConfiguration.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ConsumerRecord.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Header.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/KafkaVersion.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ProduceContext.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Producer.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ProducerConfiguration.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/RecordMetadata.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ReflectionUtils.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/package-info.java
kafka-client-factory/pom.xml
kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactory.java
kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactoryImpl.java
kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/package-info.java
kafka-impl/pom.xml
oauth-client/pom.xml
pom.xml
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/DefaultKafkaClientFactory.java

Currently KoP verifies other versions of Kafka client only by running a simple e2e test (`KafkaIntegrationTest`) that Kafka client is running inside the docker container.
This test is simple and has some flaws:
1. If we want to change the test code, we need to update the docker image.
2. We can't make use of IDE like Intellij Idea to debug the client side code.
3. It's too simple and doesn't cover the basic cases like whether the key, headers can be processed well and whether the Kafka producers/consumers of mixed versions.
And we can't test other versions just by changing the version of `kafka-clients` dependency. Because KoP server side depends on some common classes from `org.apache.kafka.common` package, which is also included in `kafka-clients` dependency. If we modified the …

Add test framework for Kafka clients of different versions

---

kafka-1-0/pom.xml
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/KafkaVersion.java

This patch allows you to build KOP on JDK11.
Without this patch the build fails with this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kafka-client-factory: Compilation failure: Compilation failure: 
[ERROR] /Users/enrico.olivelli/dev/kop/kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactoryImpl.java:[33,20] cannot access org.apache.kafka-1-0-0.clients.producer.KafkaProducer
[ERROR]   class file for org.apache.kafka-1-0-0.clients.producer.KafkaProducer not found
[ERROR] /Users/enrico.olivelli/dev/kop/kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactoryImpl.java:[41,20] cannot access org.apache.kafka-1-0-0.clients.consumer.KafkaConsumer …
```

Make build pass on JDK11

---

pom.xml

When building KoP by `mvn clean install -DskipTests`, there're a lot of warning logs like
> [WARNING] Could not transfer metadata io.grpc:grpc-api/maven-metadata.xml from/to bintray-streamnative-maven (https://dl.bintray.com/streamnative/maven): authorization failed for https://dl.bintray.com/streamnative/maven/io/grpc/grpc-api/maven-metadata.xml, status: 403 Forbidden
It's because bintray became unavailable from 2021 May 1st and KoP still contains bintray's repositories. So when building KoP, it still tried to download dependencies from bintray and 403 happened.
Remove the bintray related repositories, which are replaced by sonatype now. After this change, the build time reduced from nearly 50s to 35s.
Before:
```
[INFO] Total time:  51.529 s
[INFO] Finished at: 2021-07-21T21:57:52+08:00 …
```

Remove unused maven repositories to speed up building

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java

Fixes #618 
See https://github.com/streamnative/kop/issues/618#issuecomment-884764857 for the deadlock analysis.
- Use `ConcurrentHashMap` instead of `ConcurrentLongHashMap`. Though this bug may already be fixed in https://github.com/apache/pulsar/pull/9787, the `ConcurrentHashMap` from Java standard library is more reliable. The possible performance enhancement brought by `ConcurrentLongHashMap` still needs to be proved.
- Use `AtomicBoolean` as `KafkaTopicConsumerManager`'s state instead of read-write lock to avoid `close()` method that tries to acquire write lock blocking.
- Run a single cursor expire task instead one task per channel, since https://github.com/streamnative/kop/pull/404 changed `consumerTopicManagers` to a static field, there's no reason to run a task for each …

Fix deadlock caused by KafkaTopicConsumerManager

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java

This PR migrates #620 to branch-2.7.2 because it's hard to cherry-pick.

[branch-2.7.2] Fix deadlock caused by KafkaTopicConsumerManager

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

The KoP CI tests take much more time than CI tests of branch-2.7.2. 
The main reason is the `cleanup()` phase takes a long time, each time a test is cleaned up, it will take over 10 seconds to complete. This behavior was introduced from https://github.com/apache/pulsar/pull/10199, which made broker shutdown gracefully by default but it would take longer to shutdown.
The other reason is caused by rebalance time. According to my observes, when a Kafka consumer subscribes a topic in KoP, it will take at least 3 seconds. Finally I found it's caused by the GroupInitialRebalanceDelayMs config, which has the same semantics with Kafka's [group.initial.rebalance.delay.ms](https://kafka.apache.org/documentation/#brokerconfigs_group.initial.rebalance.delay.ms). It makes Kafka server wait longer for …

Speed up tests and fix flakiness

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

In K8s environment, the start of a KoP node might depend on a successful start of another KoP node. It's caused by the lookup request in `loadOffsetTopics`, here're the logs:
```
13:33:11.584 [pulsar-2-1] INFO  org.eclipse.jetty.server.RequestLog - 10.8.5.72 - - [08/Jul/2021:13:33:11 +0000] "GET /lookup/v2/topic/persistent/public/__kafka/__consumer_offsets-partition-0 HTTP/1.1" 307 0 "-" "Pulsar-Java-v2.8.0-rc-202106071430" 88
13:33:11.593 [pulsar-2-1] INFO  org.eclipse.jetty.server.RequestLog - 10.8.5.72 - - [08/Jul/2021:13:33:11 +0000] "GET /lookup/v2/topic/persistent/public/__kafka/__consumer_offsets-partition-0 HTTP/1.1" 307 0 "-" "Pulsar-Java-v2.8.0-rc-202106071430" 8
13:33:11.673 [pulsar-2-1] INFO  org.eclipse.jetty.server.RequestLog - 10.8.5.72 - - [08/Jul/2021:13:33:11 +0000] "GET …
```

Optimize the protocol handler start

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java

Fixes https://github.com/streamnative/kop/issues/385 
Currently if Kafka client want to list all topics, KoP will list topics under all namespaces. If users don't use all namespaces for Kafka clients, the other namespaces should not be accessed.
Add a config `kopAllowedNamespaces` to specify the allowed namespaces to list topics. If it's not set, only the default namespace is allowed.

Only allow topics under specific namespaces to be listed

---

kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Header.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java

There's a limit when `entryFormat=kafka` is configured that Kafka client can only interact with Kafka client but not Pulsar client. This PR intends to support Kafka consumer interacts with Kafka producer.
BTW, to support Kafka producer interacts with Kafka consumer, we need a feature from Pulsar's side.
Add a method `decodePulsarEntryToKafkaRecords` to convert Pulsar's metadata and payload to Kafka's `MemoryRecords`. Since it's basically migrated from the current `PulsarEntryFormatter`'s implementation, both `KafkaEntryFormatter` and `PulsarEntryFormatter` will reuse this method.
In `KafkaEntryFormatter#decode`, for each entry, first parse the `entry.format` property that is set in `KafkaEntryFormatter#encode`, if it's not `kafka`, treat it as a message of Pulsar format and use …

Support Kafka consumer for Pulsar format messages when entryFormat is kafka

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java

Fixes #647 
Pulsar will access the getProtocolDataToAdvertise of the protocol handler when constructing LocalBrokerData. If kafkaListeners is not configured with a host name, the protocols of Pulsar LocalBrokerData will not have the host name information of the kop protocol, which will cause kop to return the wrong partition leader.
`getKafkaAdvertisedListeners` will check whether the listeners contain the host name, if not, use `InetAddress.getLocalHost().getCanonicalHostName()` instead

Support pulsar to obtain the correct unconfigured hostname listeners of KafkaProtocolHandler.

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/MessageFetchContextTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessageFetchContextTest.java

Fixes #604 
When consume multi TopicPartition in one request, in MessageFetchContext.handleFetch(), tryComplete() may enter race condition
When one topicPartition removed from responseData, maybe removed again, which will cause Errors.REQUEST_TIMED_OUT
ReadEntries and CompletableFuture.complete operations for each partition are all performed by BookKeeperClientWorker- Different threads in the OrderedExecutor thread pool are executed. When the partition can read data, because the read data and decode operations will take uncertain time, the competition in this case is relatively weak; and when the partition has no data to write, and the consumer After all the data has been consumed, I have been making empty fetch requests, which can be reproduced stably at this time.
Stable steps to …

Fix KoP will cause Kafka Errors.REQUEST_TIMED_OUT when consume multi TopicPartition in one consumer request

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ConfigurationUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Fixes #644 
Using `PulsarClient` for topic lookup might encounter `TooManyRequestException` easily because all client connections share the same `PulsarClient` for topic lookup. It's also a waste of resource.
Add a common method `KafkaProtocolHandler#getTopic` for all places that need topic lookup in KoP. In this method, first use `NamespaceService.getBrokerServiceUrlAsync` to get broker's Internet address.
However, when the namespace bundle is not owned by any broker, which usually happens during a bundle unload, the `getBrokerServiceUrlAsync` might return a `LookupResult` instance whose `redirect` field is true. Pulsar client can handle this field and resend the lookup request to another broker, but Kafka client cannot do it. In this case, this PR use `PulsarClient` for topic lookup as …

Allow setting listener name for topic lookup and optimize the lookup

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java

When `KafkaTopicConsumerManager#removeCursorFuture()` returns null, it means the TCM (`KafkaTopicConsumerManager` instance) is closed accidentally. However, in this case, the TCM was not removed from `KafkaTopicConsumer.consumerTopicManagers` currently. Then next time `topicManager.getTopicConsumerManager` could still return the closed TCM.
When `KafkaTopicConsumerManager#removeCursorFuture()` returns null, remove the TCM from cache.

Remove closed KafkaTopicConsumerManager from cache

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

When there're a lot of topics, there could be a lot of `MetadataCache` instances in memory.
This bug was introduced from https://github.com/streamnative/kop/pull/488 because the Pulsar side adopted a new class `MetadataCache` as ZK cache.  However, each time `MetadataStore#getMetadataCache` is called, a new `MetadataCache` instance will be created. In KoP, it means that each time a topic lookup is performed, a new `MetadataCache` instance will be created.
Only call `MetadataStore#getMetadataCache` once when KoP starts and reuse the same `MetadataCache` instance for each `KafkaRequestHandler` instance.

Avoid creating a lot of MetadataCache instances

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Resource.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/ResourceType.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CustomOAuthBearerCallbackHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthDefaultHandlersTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java

#236 Add authorization to handleTopicMetadataRequest.
Fix #415 and #571 
When client fetch metadata need check topic permission, so we need add authorization in handleTopicMetadataRequest, and do not perform role verification in authentication.
Add a common method in `KafkaRequestHandler#authorize` , this method use `authorizer` to authorization.
Modify the authentication behavior, and do not verify the role during authentication, verify the role in fetch metadata(#571  )

[FEATURE] Add authorization to handle topic metadata request

---

docs/security.md

This PR separates authorization from authentication, and provides details of authorization configuration.

[Docs] Add authorization docs

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DirectBufferOutputStream.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/DirectBufferOutputStreamTest.java

When a Pulsar entry is decoded to Kafka record in `ByteBufUtils#decodePulsarEntryToKafkaRecords`, a NIO buffer whose initial capacity is 1 MB will be allocated from heap memory. Therefore, each time an entry is read, 1 MB heap memory will be allocated. Then the heap memory will increase very quickly and GC will happen frequently.
Kafka `MemoryRecordsBuilder` uses its underlying `ByteBufferOutputStream` field as the internal buffer whose capacity can be increased in `write` method. Even if a direct buffer was allocated by Netty's pooled direct memory allocator and its underlying `ByteBuffer` was passed to `ByteBufferOutputStream`'s constructor, if the reallocation happened, the new buffer could still be allocated from heap memory.
This PR adds a `DirectBufferOutputStream` class that …

Use pooled direct memory allocator when decoding Pulsar entry to Kafka records

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java

Fixes https://github.com/streamnative/kop/issues/678
This PR doesn't fix the test completely. It just does the trick to change the test name so that the test can ran as the first test. See https://github.com/streamnative/kop/issues/682 for tracking this issue.

Fix flaky testMutiBrokerUnloadReload by running it at first

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
pom.xml

https://github.com/apache/pulsar/pull/11804 added the custom implementations of `equals` and `hashCode` methods of `ServiceCnx`, which made KoP's spotbugs check fail with 
> Medium: io.streamnative.pulsar.handlers.kop.InternalServerCnx doesn't override org.apache.pulsar.broker.service.ServerCnx.equals(Object) [io.streamnative.pulsar.handlers.kop.InternalServerCnx] At InternalServerCnx.java:[line 1] EQ_DOESNT_OVERRIDE_EQUALS
This PR adds the overrided `equals` and `hashCode` methods by calling base class' same name methods simply. On the other hand, since the new `equals` and `hashCode` methods are based on `ctx` field and they are called when removing `Producer` from `Topic`, this PR also updates the `ctx` field of `InternalServerCnx`.

[branch-2.8.0] Bump Pulsar to 2.8.0.15

---

pom.xml

`log4j-slf4j-impl` is duplicate in `kafka-0-10` and `kafka-1-0`, because `log4j-slf4j-impl` only use by unit test, so we just change the `log4j-slf4j-impl` dependency scope to `test`.

[BUG] Fix unit test logs has multiple SLF4J bindings

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java

fixes #688 
if enable sasl/plain, the apiVersionRequest request will fail when the client use higher than the Kafka-2.0 version protocol.
Do special processing for unsupported ApiVersionsRequest like KafkaCommandDecoder's byteBufToRequest, and return UNSUPPORTED_VERSION error to the client.

[BUGFIX] handle unsupported ApiVersionsRequest when channelPrepare

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticatorTest.java

fixes #696 
#696  describes a detailed investigation of the problem and root cause of the Go Sarama client's inability to process the metadata response after passing V0 authentication caused by LengthFieldPrepender
After the go sarama client passes the v0 version authenticate, it can process other data requests normally.

[BUGFIX] Fix go sarama client with v0 handshake can successful authenticated but will failed fresh metadata

---

kafka-0-10/src/main/java/io/streamnative/kafka/client/zero/ten/Consumer010Impl.java
kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ConsumerImpl.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Consumer.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ConsumerConfiguration.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/KafkaVersion.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Producer.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/TopicOffsetAndMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopRecordsUtil.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndPulsarTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/DefaultKafkaClientFactory.java

Fixes #681 #687
#605 added a test framework for Kafka clients of different versions. However, it only added the basic e2e test, an important API commitOffset was not verified.
Add commit offset test in BasicEndToEndPulsarTest and BasicEndToEndKafkaTest in io.streamnative.pulsar.handlers.kop.compatibility package.
This feature belongs to the compatibility issue between different versions of kafka client and kop.

[FEATURE] Add commit offset test for Kafka clients of different versions

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaNonPartitionedTopicTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Fix #674
Some users want to use exists non-partitioned topic in KoP, so we need support the feature.
**Note**: Current don't support transaction.
When KoP handle `METADATA` request, if the topic is non-partitioned topic, then treat as a single partitioned topic. And when we `KafkaTopicManager#getTopic`, add a fallback to get non-partitioned topic. Also when namespace `load` or `unload`, we need clear the cache.

[FEATURE] Support non-partitioned Topic

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java

Fixes #706 
The current Kafka protocol header authentication of the high version will print the session debug log if the authentication is successful, but for the low version authentication, the session will be created after the debug log is printed.
Like the higher version of Kafka protocol header authentication, it is very useful to print the lower version of the authentication session debug log.

[MINOR] Print old client authentication session debug log

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java

This patch introduces a little refactor in order to support the implementation of a separate KOP Proxy Module:
- allow to access internal ByteBuf of KafkaHeaderAndRequest, in order to allow zero-copy request magement in the Proxy
- extract some static methods in order to use the same algorithm for mapping coordinators
Relates to #57

Refactor APIs to allow access from the Proxy module

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServerTest.java

- If the authenticated role is a proxyRole use the username as OriginalPrincipal
- remove dependency on "BrokerService" in SaslAuthenticator

Add support for passing OriginalPrincipal from Proxy

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ShutdownableThread.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DelayAuthorizationFailedCloseTest.java

Fix #668
Performing authentication is one of the most expensive operation performed in the network thread, so much so that it could end up saturating them, preventing from getting any useful work from being done.
* Support delay close on authentication failed.
* Change logs level.

[FEATURE] Support delay close on authentication failed

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIdleConnectionTest.java

#713
When there are too many idle connections on the server side, new client connections may not be created, so we need to clear idle connections over time.
Implemented using `IdleStateHandler`.

[FEATURE] Support close Idle connections when timeout

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

This bug was introduced by #541.
The `ACTIVE_CHANNEL_COUNT_INSTANCE` in `close()` should be `ALIVE_CHANNEL_COUNT_INSTANCE`

Fix ACTIVE_CHANNEL_COUNT_INSTANCE decrement twice

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java

Fixes #682
The test unit `DistributedClusterTest#testMultiBrokerUnloadReload()` is flaky. 
If the`topicManager.getTopicBroker(topic.toString())` method has exception,  the `thenCompose` supplied function will never called, In this case `stringOptional` is null, will cause `NullPointerException`. 
See docs in : https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html#thenCompose-java.util.function.Function-
Use `thenApply` to replase `thenCompose`

Fix the findBroker method may hang

---

kafka-2-8/pom.xml
kafka-2-8/src/main/java/io/streamnative/kafka/client/two/eight/Consumer280Impl.java
kafka-2-8/src/main/java/io/streamnative/kafka/client/two/eight/Producer280Impl.java
kafka-2-8/src/main/java/io/streamnative/kafka/client/two/eight/package-info.java
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/KafkaVersion.java
kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactoryImpl.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/saslplain/SaslPlainEndToEndTestBase.java

This patch adds the Kafka 2.8.0 shaded client, and enables running compatibility tests using that version as well as with Kakfa 1.0, 1.1 and 0.10.
This way we will have more coverage of existing Kafka clients.

Add Kafka client 2.8.0 tests

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java

Fixes #732 
When exiting kop, kopEventManager should be closed.

[BUGFIX] Shut down KopEventManager when closing kop

---

docs/configuration.md
docs/security.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TenantContextManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/KafkaPrincipal.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/ResourceType.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationKafkaMultitenantTenantMetadataTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java

This patch introduces a new  configuration flag `kafkaEnableMultitenantMetadata` that makes KOP use separate namespaces for Metadata Operations.
Motivation:
Currently KOP cannot be used in clusters where you need strong tenant isolation because we are sharing the system metadata topics.
We need a way to totally isolate the traffic and data storage per tenant.
High level overview:
The Client authenticates passing as username the Pulsar tenant for metadata operations.
We use such tenant for every metadata operation, and so we isolate the traffic of each tenant.
Summary of changes:
- Implement capture of "username" in SASL authentication
- Introduce the concept of "tenant" on KOP Hander: it is the "username" if authenticated otherwise it is `kafkaMetadataTenant` (if the username is in the …

Implement Tenant Aware Metadata Topics

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java

With the new Tenant Aware Metadata Topics feature (https://github.com/streamnative/kop/commit/d4f996039cb3f52bed5bd2cc59d626ecbb7984ee) now we initialise the OffsetAndTopicListener listener lazily.
Before this patch `OffsetAndTopicListener` was responsible for invalidating the `KopBrokerLookupManager` caches.
But as we initialise it lazily it would be possible to miss some cache invalidations.
This patch introduces a dedicated listener `CacheInvalidator` that invalidates the caches for every change that is detected.

Invalidate KopBrokerLookupManager  caches separately from GroupManagement listener

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/EndPointTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KafkaStreamsTestBase.java

Fixes #669
Fixes #574
To support multiple listeners with multiple protocols, we need to set follow configration, and deprecated `kafkaAdvertisedListeners` and `kafkaListenerName`.
> kafkaListeners=internal://0.0.0.0:9092,internal_ssl://0.0.0.0:9093,external://0.0.0.0:19002,external_ssl:0.0.0.0:19003
> kafkaProtocalMap=internal:PLAINTEXT,internal_ssl:SSL,external:PLAINTEXT,external_ssl:SSL
> advertisedListeners={pulsar's listeners},internal:pulsar//192.168.1.10:9092,internal_ssl:pulsar//192.168.1.10:9093,external:pulsar//172.16.1.10:19002,external_ssl:pulsar://172.16.1.10:19003
1. Define the listenerNames and port of each listenerName in `kafkaListeners`
2. Define the listenerNames and protocol of each listenerName in `kafkaProtocalMap`
3. Add listenerNames and advertised address of each …

support multiple listeners with multiple endpoints

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeKafkaFormatTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimePulsarFormatTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestTypeTest.java

1. In SaslAuthenticator, we should keep the log level as debug, because authentication is a very frequent occurrence in high-traffic systems, which is often encountered in kafka, the connection and disconnection between the client and the server has been happening all the time . If we need to troubleshoot problems, we can dynamically adjust the log level.
2. Before executing the debug, keep judging whether to enable the debug, even if log4j2 writes the log asynchronously, it can avoid generating unnecessary LogEvent.

Adjust the log level

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
pom.xml

This PR migrates https://github.com/streamnative/kop/pull/692 for master branch.
Since we will upgrade Pulsar to 2.9.0 later, which might bring more incompatibilities, this PR migrates the fix for branch-2.8.1 first.

Bump pulsar to 2.8.1.0

---

docs/kop.md

Currently the SN Hub doesn't modify the content, so the document of older version releases will still link to master branch.
Replace the `master` with `branch-{{protocol:version}}` in `docs/kop.md`.

Link to branch-x.y.z.m instead of master branch

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SystemTopicClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java

The `PulsarClient` object returned by `PulsarService#getClient` doesn't change the default `statsIntervalSeconds` config, Therebefore, each producer or reader created in `GroupMetadataManager` will has an internal `ProducerStatsRecorderImpl` or `ConsumerStatsRecorderImpl` object, which triggers a `TimerTask` whose period is 60 seconds. It's a waste of CPU usage especially when the offset topic's partitions number is large.
Since we have already defined our own `PulsarClient` wrapper (`LookupClient`) for topic lookup, this PR adds a common abstract class `AbstractPulsarClient` to customize the client config. Then add a `SystemTopicClient` class that configures `statsIntervalSeconds` with zero value to disable stats recorder.

Disable stats recorder for PulsarClient in group coordinator

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java

Currently KoP don't support authorization when users use adminClient to create topic or delete topic. So we need support this feature. 
In Pulsar, create or delete topic should have tenantAdmin or SuperAdmin permission, this implementation will follow the pulsar way.
* Add authorization to `handleCreateTopics`
* Add authorization to `handleDeleteTopics`
* Add new test units for create or delete topic permissions
* Add new test units for create topic with authorization
* Add new test units for delete topic with authorization

[FEATURE] Add authorization to create topic and delete topic requests

---

docs/configuration.md
docs/kop.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java

https://github.com/streamnative/kop/pull/690 supports non-partitioned topics and https://github.com/streamnative/kop/pull/742 supports multiple listeners and marks some configs as deprecated, so the current documents are outdated. 
Even if KoP supports non-partitioned topics now, it's still better to configure `allowAutoTopicCreationType` with `partitioned` by default. This PR modified the explanation for the reason.
This PR also adds docs for how to enable multiple listeners and updates the related configuration docs.
In addition, https://github.com/streamnative/kop/pull/742 marks `kafkaListenerName` as deprecated, but it also makes this config not work anymore. So this PR removes the config and related tests.

Update docs for multiple listeners and non-partitioned topic support

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java

Fixes #756 
#735  implements tenant aware metadata topics. It instantiates a KopEventManager for each GroupCoordinator. In fact, this is wrong. KopEventManger should be a global event handler. Unless we need to use KopEventManager to implement some other models, we A single instance should be kept to handle events.
1. Keep KopEventManager as a single-threaded event model.
2. Leave a discussion on KopEventManager#307

[BUGFIX] Keep KopEventManager as a single-threaded event model

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopEventManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Since most of units test don't depend of transaction, we can disable transaction by default.
* Disable transaction by default on units test
* Modify some test, add new method called `triggerTopicLookup`, to make sure lookup call first, it will loading `NamespaceBundle` to the `OwnershipCache`, otherwise getTopic will failed in `OwnershipCache.getOwnedBundle()`.

Disable transaction by default on units test

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java

Fixes: #761
In K8S environment, load transaction topics when start KafkaProtocolHandler might crash, because to start a KoP node might depend on a successful start of another KoP node.
See Related PR : #627
The most important change is to remove the `loadTxnLogTopics ` method.
Addition change is add a method to wait txnLog load in units test.

[BUGFIX] Fix loadTxnLogTopics might crash in K8S environment

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaResponseUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

KafkaStreams uses the DeleteRecords API to truncate topics to the very end of the topic.
https://github.com/apache/kafka/blob/ba0ebca7a516d4179b6327ddc60b0b49b1265347/streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java#L441
This patch implements DeleteRecords, using the `truncateAsync` API in Pulsar introduced in 2.8.0.
we cannot make it work for arbitrary offsets, by the way this implementation is still useful, at least for KStreams or for Kafka Users who want to empty a topic.
Please note that Kafka Streams does not break without this feature, because it tries to delete the records in a best effort way.
Fixes #867

[Issue 867]: Implement minimal DeleteRecords (KStreams support)

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ErrorsAndData.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java

Currently, KoP support transaction but don't have units test to cover transaction coordinator code behavior, for future maintain, we should add units test from  Kafka.
* Fix `handleInitProducerId` behavior.

[Transaction] Migrate transaction coordinator handleInitProducerId tests and fix behavior

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java

Currently, KoP support transaction but don't have units test to cover transaction coordinator `handleAddPartitionsToTransaction` behavior, for future maintain, we should add units test from Kafka.
**In addition**: `handleAddOffsetsToTxn ` should response  `AddOffsetsToTxnResponse`, previous implementation use `AddPartitionsToTxnResponse` to response.
* Fix `handleAddPartitionsToTransaction` behavior.
* Fix `handleAddOffsetsToTxn ` wrong response.

[Transaction] Fix transaction coordinator handleAddPartitionsToTransaction behavior and migrate tests

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java

Master issue: #830
The `GroupCoordinatorTest` spend too much time to start mock pulsar and shutdown mock pulsar in each tests. See: 
https://github.com/streamnative/kop/issues/830#issuecomment-949259927
1. Each time we start new test method, just restart `GroupCoordinator`, instead of restart new mock pulsar.
2. Remove unused consumer
This PR speed up the `GroupCoordinatorTest`, reduce test time from **500s** down to **14s**
**Before** : 
```text
[INFO] Running io.streamnative.pulsar.handlers.kop.coordinator.group.GroupCoordinatorTest
[INFO] Tests run: 63, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 499.022 s - in io.streamnative.pulsar.handlers.kop.coordinator.group.GroupCoordinatorTest
```
**After** : 
```text
[INFO] Running …
```

Speed up group coordinator tests

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java

Currently, KoP support transaction but don't have units test to cover transaction coordinator `handleEndTransaction ` behavior, for future maintain, we should add units test from Kafka.
* Fix `handleEndTransaction ` behavior.

[Transaction] Fix transaction coordinator handleEndTransaction behavior and migrate tests

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java

Currently, KoP support transaction but don't have units test to cover transaction coordinator code behavior, for future maintain, we should add units test from  Kafka.
* Use get/set method to get or set the `EpochAndTxnTransitMetadata` value.
* Fix some logs content, is should have value.
* Fix `isValidProducerId ` method bad behavior.
* Fix `prepareInitProducerIdTransit` might get null date.

[Transaction] Migrate remains of transaction coordinator handleInitProducerId tests and fix behavior

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetFinder.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java

Fixes https://github.com/streamnative/kop/issues/876
There is a corner case that `MessageMetadataUtils.getOffsetOfPosition` fails with `NonRecoverableLedgerException`.
If a managed ledger has multiple ledgers that are all expired. After an automatically rollover controlled by max rollover time), a new empty ledger will be created, then the previous ledgers will be removed. However, a rollover doesn't change the `lastConfirmedEntry`, in `ManagedLedgerImpl#getFirstPosition`, if the first ledger's id is greater than the `lastConfirmedEntry`, the returned position's ledger id will be the same with the `lastConfirmedEntry`'s ledger id. In addition, KoP applies `ManagedLedgerImpl#getNextValidPositionInternal` to the first position. In this method, if the position's ledger id is the same with …

Fix list offsets failure when ledgers are removed by a rollover operation

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

**Motivations**
This patch will allow KOP users to use kSQL (https://ksqldb.io/) 
Problems with KOP 2.9.x
- the KSQL Server requires DESCRIBE_CONFIGS to return a couple of configurations
- the KSQL Server tries to override some configurations, that are not under control of KOP, let's ignore such calls
**Modifications**
- Add dummy support for the ALTER_CONFIGS API, ignoring everything
- Add dummy support for DESCRIBE_CONFIGS for the BROKER configuration

Implement dummy ALTER_CONFIGS and DESCRIBE_CONFIGS for Broker - minimal KSQL Server support

---

docs/configuration.md

Fixes https://github.com/streamnative/kop/issues/889

[Docs] multiple listeners for KoP 2.9.0

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionConfig.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionState.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java

#896
1. Support transactional Id expiration
2. Refactor `TransactionStateManagerTest`
3. Remove `txnLogStoreAndTCImmigrationTest`, it will add back in other PR.
4. Use TransactionConfig `TransactionMetadataTopicName` instead of `Topic.TRANSACTION_STATE_TOPIC_NAME`.

[Transaction] Support transactional Id expiration

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java

Master issue: #897
Currently, KoP support transaction but don't have units test to cover transaction coordinator code behavior, for future maintain, we should add units test from  Kafka.
* Fix `endTransaction` behavior.

[Transaction] Migrate transaction coordinator test and fix behavior

---

README.md
docs/kop.md

https://github.com/streamnative/kop/pull/389 exposed the metrics for KoP and added the docs. However, users cannot click into the metrics docs in the main web page.
Add the link of metrics docs to README.md. In addition, sync docs/kop.md with README.md so that upgrade.md and reference-metrics.md can both be navigated from SN hub. Then remove the **Upgrade** section because it's duplicated with upgrade.md.

[Docs] Add Monitor KoP link to main page

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java

In `TransactionStateManager` we use `CompletableFuture` to simplify async programming, but `TransactionStateManager`  all operates should sync run in scheduler.
1. Keep sync when load or remove transaction log in partition.
2. Add a warning log when `loadTransactionsForTxnTopicPartition` remove leavingPartitions success for future debugging.
Add units test cover changes.

[Transaction] Fix transaction state manager might have race condition

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/UpgradeTest.java

https://github.com/streamnative/kop/pull/907 support skipping old messages without BrokerEntryMetadata (message index).  Even if the client gets the wrong offset from old `__consumer_offsets` topic, when KoP handles FETCH request, it will still skip these messages and fetch messages from offset 0. This behavior should be disabled by default because the KoP upgrade might not be aware by client so that users might find some messages are lost after a long time.
- Add a `skipMessagesWithoutIndex` to configuration. Keep the original behavior in `asyncFindPosition` and `getOffsetOfPosition` if it's false (by default).
- Enable the `skipMessagesWithoutIndex` in `UpgradeTest` to make tests pass.

Add skipMessagesWithoutIndex option to enable skipping old messages

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataConstants.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/MessageFetchContextTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/KopTopicTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java

**Problem**
When you enable multi-tenancy aware mode (enabled by default) the user that is not on the "default" tenant must use fully qualified topic names.
**Changes**
In this change we remove the static 'namespacePrefix' variable from KopTopic and we explicitly pass the 'namespacePrefix' every time we construct a KopTopic instance.

Multi Tenant Aware: Apply current tenant when using short topic name

---

docs/upgrade.md

Add the docs about when should we enable `skipMessagesWithoutIndex`, which was introduced from https://github.com/streamnative/kop/pull/916.

[Docs] Add docs for skipMessagesWithoutIndex

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java

`KafkaRequestChannel#close` calls `KafkaTopicManager#removePersistentTopicAndReferenceProducer` for each topic in cache. But `CompletableFuture#get` is called in `removePersistentTopicAndReferenceProducer`, which is called in an I/O thread. It will lead to a deadlock issue.
Instead of calling `get` for a `PersistentTopic` object, call `thenAccept` and `exceptionally` method on the future to do the cleanup work for `PersistentTopic`.

Avoid waiting a future when channel is closed

---

kafka-0-10/pom.xml
kafka-0-10/src/main/java/io/streamnative/kafka/client/zero/ten/Consumer010Impl.java
kafka-0-9/pom.xml
kafka-0-9/src/main/java/io/streamnative/kafka/client/zero/nine/Consumer009Impl.java
kafka-1-0/pom.xml
kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ConsumerImpl.java
kafka-2-8/pom.xml
kafka-2-8/src/main/java/io/streamnative/kafka/client/two/eight/Consumer280Impl.java
kafka-3-0/pom.xml
kafka-3-0/src/main/java/io/streamnative/kafka/client/three/zero/Consumer300Impl.java
kafka-client-api/pom.xml
kafka-impl/pom.xml
oauth-client/pom.xml
pom.xml
tests/pom.xml

Fixes https://github.com/streamnative/kop/issues/924
The current dependency management is bad. We should ensure new added module doesn't depend on some unnecessary dependencies.
The main changes are:
- Move all dependencies from `<dependencies>` under `<dependencyManagement>` block in root `pom.xml`.
- Add required dependencies for each module.
In addition, some minor changes were made:
1. Remove google common dependencies from modules of different Kafka version, like `kafka-0-9`. It's redundant to introduce a dependency just for a `Maps.newHashMap` method.
2. Rename `mavem-shade-plugin.version` to `maven-shade-plugin.version`.

Adjust pom.xml for dependency management

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedProduceAndFetch.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingTopicFutures.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TenantContextManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/AppendRecordsContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/package-info.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Currently, the KoP store message logic is in `KafkaRequestHandler`, to avoid duplicate code and easier to support idempotent produce, we must refactor the message storage logic.
* Refactor message storage logic.
* The `ReplicaManager` is a public interface to store messages, we should always use `ReplicaManager` to store the message in any situation.
* `PartitionLog` mapping to Kafka is `Log`, the reason for using this name is to avoid naming conflict, like: `log.debug()`.
* `PartitionLogManager` hold all `PartitionLog`, key is full partition name, value is `PartitionLog`.
* Add fetch operation

Split the message storage logic into independent classes

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java

This patch adds failure handling on TransactionMarkerChannelHandler.
In case of failure on the socket we must fail every pending request, otherwise the system will be stuck

Improve TransactionMarkerChannelManager

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaNonPartitionedTopicTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java

In KoP the transaction config might confuse users, and some config in the future might duplicate with Pulsar, we should add a prefix to distinguish it. 
Add prefix for transaction config.

Add transaction config prefix

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java

**Motivation**
When you enable JWT token authentication transactions do not work because transactions need broker-to-broker communication but there is currently no support for the SASL handshake.
**Changes**
Now when you enable authentication and you configure Token Authentication for Broker-To-Broker communications in Pulsar, we perform SASL PLAIN authentication while preparing the connection to other brokers.
**Tests**
I have extended existing SASL tests in order to use Transactions. I have copy/pasted some parts of the TransactionTest, but there was not enough code to make sense to share the test code.

Transactions: implement support for JWT token authentication between brokers

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerTest.java

Fix https://github.com/streamnative/kop/runs/4425667410?check_suite_focus=true#step:5:283
#950
MockZookeeper API has changed, the `CreateMode` shouldn't be null. We should use MetadataStore instead of mockZooKeeper since KoP already remove all zkClient usage.
Use MetadataStore instead of mockZooKeeper in ProducerIdManagerTest

Fix NPE problems caused by mockZooKeeper API changes when dump version to 2.8.1.26

---

pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerTest.java

Fix #950
https://github.com/apache/pulsar/pull/13066 introduced a breaking change to the `MockZooKeeper` API and causes test failure. 
* Fix failure test
* Upgrade pulsar version to 2.8.1.0

Bump pulsar version to 2.8.1.0

---

kafka-payload-processor/pom.xml
kafka-payload-processor/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaPayloadProcessor.java
kafka-payload-processor/src/main/java/io/streamnative/pulsar/handlers/kop/package-info.java
pom.xml
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java

It's recommended to configure `entryFormat=kafka` for better performance among Kafka clients in KoP. However, since it writes the original messages of Kafka format to BK, Pulsar consumer cannot consume these messages.
[PIP-96](https://github.com/apache/pulsar/wiki/PIP-96%3A-Message-payload-processor-for-Pulsar-client), which will be included in Pulsar 2.9.0, introduced a payload processor for Pulsar consumer. Based on PIP-96, this PR intends to add a payload processor for messages of Kafka format.
- Add a `kafka-payload-processor` module that contains the implementation of `KafkaPayloadProcessor`.
- Add tests to cover null values, keys and headers.

Add Kafka payload processor 

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetConfig.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/TopicNameUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

`public/default/__consumer_offsets` is incorrectly considered as an internal metadata topic
1. Based on #793 , we can control whether users are allowed to access the `metadata` namespace
2. I am still not sure whether we should allow users to access the kafka topics which under other namespaces (such as `default` ) have the same name with the internal topics. The current implementation of the kafka topics under the `default` namespace have the same name with the internal topics will be used as the internal topics and returned to the kafka client.
3. However, we should bind to the `metadata` namespace when judging the `internal` topics.
This PR solves problem 3. When problem 3 is solved, we can treat the kafka topics which under other namespaces have the same name with the internal topics …

[BUGFIX] Fix the internal topics should be controlled in the meta namespace

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java

**Motivation**
When you have a system with many independent tenants having a global configuration that is the same for every tenant is problematic.
Therefore there are cases in which you don't want that the PH creates namespaces or overrides the configuration, because there is some other component (like a separate control plane) that is in charge of managing all the system configurations for each tenant.
**Changes**
Add a new configuration option `kafkaManageSystemNamespaces` to disable any operation about creating namespaces or setting any configuration.
This option will allow to move the management of such things to an external entity.

Implement ability to not handle namespaces automatically: kafkaManageSystemNamespaces

---

docs/cve_list.md

Fixes #975 
Starting from #926, kop will use the log4j2 version that pulsar relies on, but before this (2.8.1.26) kop is affected by this vulnerability, just upgrading the log4j2 version that pulsar relies on is not enough.

Add cve_list md for CVE-2021-44228

---

kafka-impl/pom.xml
pom.xml
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java

This PR migrates https://github.com/streamnative/kop/pull/926 to branch-2.7.3. It also solves the log4j vulnerability (CVE-2021-44228) for branch-2.7.3.
In addition, `SchemaRegistryTest` is ignored for now.

[branch-2.7.3] Adjust pom.xml for dependency management

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java

In AdminManager there are some points in which we are not using correctly CompletableFuture.
This patch fixes deletePartitionedTopic and a couple of other parts.
This patch is trivial rework, no need to add tests

AdminManager: handle properly async deletePartitionedTopic

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

#908
In the current implementation, list topic and list offset might get the wrong response, because the authorized future is not finished yet. We need to make sure to authorize future finish correctly.
* Ensure all future is finished when the response

Fix list topic and list offset behavior

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/KafkaPrincipal.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationMockTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java

The current implementation of authorizing is using Pulsar's default authorization provider. For future maintenance, we better use the `AuthorizationService`. because not all users want to use Pulsar's default authorization provider.
1. Split CREATE, DELETE and ALTER.
2. Use `AuthorizationService` instead of Self-implementation authorization.

Use pulsar AuthorizationService to authorize

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

Fixes #908
In the current implementation, list topic and list offset might get the wrong response, because the authorized future is not finished yet. We need to make sure to authorize future finish correctly. 
The previous fix only checked `allTopicMap` size, but we are traverse allTopicMap's value lists. So the same case might be failed.
* Ensure all future is finished when the response

[BUGFIX] Fix list topic behavior

---

kafka-payload-processor-shaded/pom.xml

Fix upload rule failure during the release process:
```
Error:  Rule failure while trying to close staging repository with ID "iostreamnative-1043".
Error:  
Error:  Nexus Staging Rules Failure Report
Error:  ==================================
Error:  
...
Missing: no javadoc jar found in folder
...
```

[Release] Fix javadoc missing bug

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java

With this patch when you configure kafkaAdvertisedListeners you can use the special placeholder `advertisedAddress` that picks up the value configured for `advertisedAddress` in broker.conf.
Something like:
`kafkaAdvertisedListeners=PLAINTEXT://advertisedAddress:9092`
Without this placeholder you have to inject the value using other external means, like adding stuff to the Helm Chart (status.podIP) and it is not trivial.

Implement placeholder 'advertisedAddress' in kafkaAdvertisedListeners

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

Currently when the metrics related to Kafka requests are updated, a `PrometheusStatsLogger` will be created each time a request arrived.
```java
requestStats.getStatsLogger()
.scopeLabel(KopServerStats.REQUEST_SCOPE, apiName)
```
The `StatsLogger#scopeLabel` method calls `scope` method:
```java
public StatsLogger scope(String name) {
return new PrometheusStatsLogger(provider, completeName(name), labels);
}
```
The newly created `PrometheusStatsLogger` object is nearly the same with the caller itself except the name. The shared `provider` field is responsible to maintain the cache of Prometheus stats.
Therefore, there is no need to create another object if the name keeps the same. This PR is to avoid the redundant small object creations of `PrometheusStatsLogger`.
Maintain a …

Maintain a StatsLogger map to avoid creating new object every time

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java

Fixes #1038
controller in METADATA response did not return the advertised listener, which cause create topic fail.

fix create topic fail when using advertised listener

---

docker-compose.yml
docs/kop.md

Master issue: #1043
This PR adds a `docker-compose.yml` in project directory and the related docs for how to start KoP in Docker.

Add docker compose example and docs for KoP standalone

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java

There is a thread safety issue for `MessageFetchContext`. The instance of that this class could be accessed by different threads. For example, I added some logs to each method and saw the following output:
| Thread name                                 | Method name             |
| ------------------------------------------- | ----------------------- |
| pulsar-io-18-12                             | `MessageFetchContext`   |
| pulsar-io-18-12                             | `handleFetch`           |
| pulsar-io-18-12                             | `handlePartitionData`   |
| pulsar-io-18-12                             | `checkOffsetOutOfRange` |
| BookKeeperClientWorker-OrderedExecutor-10-0 | `readEntries`           |
| BookKeeperClientWorker-OrderedExecutor-10-0 | `handleEntries`         |
| …

Fix thread safety issue for MessageFetchContext

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java

Fixes: #1056
The `testMultiBrokerProduceAndConsumeOnePartitionedTopic` test method fails sporadically. Because the sometimes delete topic will timeout. link PR: https://github.com/apache/pulsar/pull/14060
* remove the call of `deletePartitionedTopic`

[Test] Fix flaky-test: DistributedClusterTest.testMultiBrokerProduceAndConsumeOnePartitionedTopic

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

Fixes #1053 
Currently, the idempotent producer test is not stable, because consumers don't provide orderly consumption, we should add a test to verify idempotent produce, and remove consumption orderly check.
* Add test for an idempotent producer in KafkaApiTest
* Remove consumption orderly check

[Test] Fix idempotent producer test

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

Fixes https://github.com/streamnative/kop/issues/1050
Currently `ReplicaManager#getPartitionLog` transfers exceptions thrown from `PartitionLog#appendRecords` to Kafka's error code by calling `Errors.forException` and treats the unknown error as `KAFKA_STORAGE_ERROR`. However, the exception is thrown from broker side:
- Control records are sent by `ManagedLedger#asyncAddEntry`, the `ManagedLedgerException` will be thrown if failed.
- Normal records are sent by `PersistentTopic#publishMessages`, the `BrokerServiceException` that wraps `ManagedLedgerException` will be thrown if failed.
After a bundle unload event, some entries might still be cached in the managed ledger. In this case, all entries will be failed with `ManagedLedgerAlreadyClosedException`. However, if Kafka producer received …

Return NOT_LEADER_FOR_PARTITION when managed ledger's state is wrong

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java

This patches fixes a NPE that happens during bundle unload
> 17:25:52.106 [AsyncHttpClient-62-1] ERROR io.streamnative.pulsar.handlers.kop.KopBrokerLookupManager - No node for broker 10.8.3.4:6650 under loadBalance
> 17:25:16.881 [pulsar-client-io-47-1] WARN  io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - [[id: 0x3ed2997b, L:/10.8.5.5:9092 - R:/10.8.4.131:58416]] Request RequestHeader(apiKey=METADATA, apiVersion=7, clientId=consumer-sub-000-pcryMaM-4, correlationId=7703): Exception while find Broker metadata
> java.util.concurrent.CompletionException: java.lang.NullPointerException
>         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
>         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) …

Fix NPE during lookup during bundle unload

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java

The `isMarkerMessage` method is used for `ReplicatedSubscriptions`, we should use `isMarkerMessage` in KoP.
Do not override `isMarkerMessage ` method in KoP MessagePublishContext.

Remove isMarkerMessage method in KoP MessagePublishContext

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetResetTest.java

Bump Pulsar version to 2.10.0.0-rc2 and fix the incompatibility issues introduced from https://github.com/apache/pulsar/pull/14004 and https://github.com/apache/pulsar/pull/12401.

Bump Pulsar version to 2.10.0.0-rc2

---

kafka-payload-processor-shaded-tests/src/test/java/io/streamnative/pulsar/handlers/kop/MockedMessagePayloadContext.java
pom.xml

https://github.com/apache/pulsar/pull/10478 introduced an API change to `MessageImpl#create`, which is included in 2.10.0.0-rc4, we need to fix the conflict.

Bump Pulsar version to 2.10.0.0-rc4

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java

This PR is a follow up bug fix of https://github.com/streamnative/kop/pull/1042 for branch-2.8.2. It also migrate some util methods and tests from https://github.com/streamnative/kop/pull/864.

Fix CreateTopics failure when kafkaAdvertisedListeners are different with kafkaListeners

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java

Fixes  #1090
Currently, even if we config kafkaTransactionCoordinatorEnabled=false, the Kafka transaction coordinator is still started.
It happened when the broker has a consumer fetch message.
When `kafkaTransactionCoordinatorEnabled = false`, ensure the transaction coordinator don't start.

[Transaction] Able to disable transaction coordinator

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

Related to this #1092 
1. The current brokers metadata is maintained in the AdminManager, and obtaining the controllerId from here can ensure data consistency.
2. Avoid extra complex parsing listeners and handling exceptions.
3. The node ID is calculated from the hostname and port hash. If kop is not configured with ip or hostname, the program will automatically obtain the hostname. One of the problems is: when kop is running, if a new hostname address is added to the local domain name self-resolution, and as for the first position, it may cause the program to return a different host alias, the controller node id will inconsistent with the Broker cache in metadataStore. You can see the PR #648 I submitted a long time ago.
4. Reuse `testMetadataRequestForMultiListeners` test validation …

Optimize the way to get the controllerId

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/ResourceType.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java

Fixes #1068 
Currently, we are using lookup to authorize the list topic permission, we should follow the pulsar way by using `validateNamespaceOperation(namespaceName, NamespaceOperation.GET_TOPICS);` to check the permission.
List topic use pulsar GET_TOPICS permission

[Authorization] List topic mapping to pulsar GET_TOPICS permission

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java

**Modifications**
- use a shared threadpool
- lazily start the drainQueuedTransactionMarkers activity only when needed
- set period to 100ms (instead of 1ms)
**Result**
If a tenant never uses transactions, then you never start the background activity, also we are able to scale the number for active tenants.
A future improvement may be to shutdown the activity when a tenant is idle for a while

Transactions: don't create a thread per-tenant

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java

**Motivation**
During OMB testing @dave2wave noticed that the BookKeeperClientScheduler-OrderedScheduler-X-Y thread pool is busy in doing decoding work (from Pulsar -> Kafka) and this is something that may limit the efficiency of the system because that threadpool handles all the BookKeeper activities.
**Modifications**
With this patch we are performing the "decoding" from Pulsar -> Kafka (con the consumer code path) in a threadpool that is not the BookKeeper Ordered Executor pool (BookKeeperClientScheduler-OrderedScheduler-X-Y).
**Results**
With this patch @dave2wave reported far better performances using OMB:
> the test results show the BookKeeperClientWorker-OrderedExecutor is working much less than before. It is about 40-45% cpu in our OMB tests now. The equivalent Pulsar workload is …

Fetch: do not decode data in critical BookKeeper OrderedExecutor thread

---

pom.xml

The https://github.com/apache/pulsar/pull/12600 changed behavior. 
Before this change, only tenant admin allow to list topics, after https://github.com/apache/pulsar/pull/12600, it allows consume permission list topics.

Bump Pulsar version to 2.9.2.1

---

pom.xml

The https://github.com/apache/pulsar/pull/12600 changed behavior. 
Before this change, only tenant admin allow to list topics, after https://github.com/apache/pulsar/pull/12600, it allows consume permission list topics.

Bump Pulsar version to 2.8.2.0

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java

Fixes: #1053
After examining the timeout test log, no blocking phenomenon was found. So the current solution is to increase test idempotent produce timeout time. Maybe it took too much time to send 1000 messages.

[flaky-test] Increase test idempotent produce timeout time

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

Optimize the way to get the controllerId to branch-2.8.2

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

This is fix for a regression introduced by fbd91a8880a10af0996aeac15d8de0b38712ad07
This is the error I am seeing in a system test that uses KSQLDB.
It refers to this line https://github.com/datastax/starlight-for-kafka/blob/a23423388ed5b476e3f30870370a066814cbd484/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java#L678 
> java.lang.IllegalStateException: Duplicate key persistent://public/default/_confluent-ksql-ktool_ksqldb__command_topic (attempted merging values _confluent-ksql-ktool_ksqldb__command_topic and _  (logs truncated.....)
> at java.util.stream.Collectors.duplicateKeyException(Collectors.java:133) ~[?:?]                                                                                                               > at …

Handle duplicate topic names requests in MetadataRequest

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java

Fixes: #1137 
The `ManagedLedgerImpl#asyncFindPosition` method might return future null, when we use it we should check position is null first.
Add NULL check.

Fix NPE when managed ledger find entry failed

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/NamespaceBundleOwnershipListenerImpl.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicOwnershipListener.java

Fixes https://github.com/streamnative/kop/issues/1134
In KoP, when namespace bundle ownership changes, there's no need to get the owned non-persistent topics, while `getOwnedTopicListForNamespaceBundle` tries to get all owned topics. There is a bug when getting non-persistent topics at Pulsar side and exceptions might be thrown in the bundle listener's callback, which makes KoP not work well for the bundle load or unload events.
In addition, there are multiple implementations of `NamespaceBundleOwnershipListener` that are registered to the `NamespaceService`. Each listener calls the `getOwnedTopicListForNamespaceBundle` method, this is redundant.
- Only retain a common implementation of `NamespaceBundleOwnershipListener`. Implement a `getOwnedPersistentTopicList` to get only persistent …

Avoid listing non-persistent topics and optimize the bundle listener

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

After https://github.com/streamnative/kop/pull/1107 was cherry-picked into branch-2.8.2, some tests of `KafkaListenerNameTest` are failed. Because that PR forgot to migrate the following code:
https://github.com/streamnative/kop/blob/51563feb582424251c8a8345ed9a7606546cf77e/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java#L792-L796
After that when the advertised listener is different with the listener, the brokers field in `MetadataResponse` doesn't contain the advertised listener, while the leader and ISR in `MetadataResponse.PartitionMetadata` use the advertised listener. Then Kafka client won't be able to find the advertised listener in brokers field.
Add the partition leader's node to the brokers field if the brokers field doesn't contain the node.

Fix NOT_COORDINATOR error caused by wrong brokers in Metadata response

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EncodePerformanceTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogTest.java

Fixes: #1147
See: #1147
The NPE happened when `KafkaTopicManager#references` removed the producer before `getReferenceProducer`. 
Use `computeIfAbsent` to make sure we can get a producer instance before we use it.
This is a bug fix no need for docs.

Fix npe when update producer states

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java

Fixes #464 
This patches prevent these errors in the logs:
```
22:10:10.220 [pulsar-client-io-35-1:org.apache.pulsar.client.impl.ClientCnx@282] WARN  org.apache.pulsar.client.impl.ClientCnx - [localhost/127.0.0.1:15002] Got exception java.lang.IllegalStateException: Some required fields are missing
at org.apache.pulsar.common.api.proto.SingleMessageMetadata.checkRequiredFields(SingleMessageMetadata.java:478)
at org.apache.pulsar.common.api.proto.SingleMessageMetadata.parseFrom(SingleMessageMetadata.java:473)
at org.apache.pulsar.common.protocol.Commands.deSerializeSingleMessageInBatch(Commands.java:1635)
at org.apache.pulsar.client.impl.ConsumerImpl.receiveIndividualMessagesFromBatch(ConsumerImpl.java:1257)
at org.apache.pulsar.client.impl.ConsumerImpl.messageReceived(ConsumerImpl.java:108 …
```

KafkaMessageOrderKafkaTest: prevent spammy logs due to wrong entry in Kafka format received by the Pulsar consumer

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

Currently, when store group id failed, the `resultFuture` will never complete, it will cause client request timeout, we should continue the subsequent operations whether store group id is successful or not. Since the group id is only used to collect consumer metrics.
1. Continue the subsequent operations whether store group id is successful or not.
2. Add units test to verify it.

Fix when store group id failed the find coordinator future never complete

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java

Fixes #1161
The `testDeletePartition` relies on the fact that `h` has been sent to partition 1. However, Kafka's default partition assignor cannot guarantee that. See example debug logs:
```
KafkaProducer send 'g' to test-delete-partition-partition-1@3
KafkaProducer send 'h' to test-delete-partition-partition-0@3
KafkaProducer send 'i' to test-delete-partition-partition-1@3
```
These three messages (`g`, `h`, `i`) were sent in a round robin way. However, `h` was sent to partition 0 while `g` and `i` were sent to partition 1, which was deleted later. Then the Kafka consumer can only receive 1 message and `receiveMessages` will be stuck because the expected number of messages is 2.
Send `g`, `h`, `i` to the specific partitions directly using the following overload of `ProducerRecord`: …

Fix flaky testDeletePartition by sending to specific partitions

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java

It's a workaround for https://github.com/streamnative/kop/issues/1053. Disable the test to make CI stable.
Only run `testIdempotentProducer` for non-batch send.

Disable testIdempotentProducer for batch send

---

pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java

Fixes #1175
The `ManagedLedger#rollCurrentLedgerIfFull` can only work when the managed ledger's state is `LedgerOpened` since https://github.com/apache/pulsar/pull/14664. The corner case described in https://github.com/streamnative/kop/pull/894 is still possible when some entries are sent but not persisted after a rollover and retention works. Therefore, we should still keep the `testListOffsetForEmptyRolloverLedger` to avoid the regression in KoP.
- Bump Pulsar to 2.10.0.0-rc12, which includes https://github.com/apache/pulsar/pull/14664
- Change the managed ledger's state to `LedgerOpened` in `testListOffsetForEmptyRolloverLedger`.

Bump pulsar to 2.10.0.0-rc12 and fix testListOffsetForEmptyRolloverLedger

---

docs/implementation.md

Fixes #1058
The implementation documents are wrong and might make users confused.
- Replace the legacy implementation of Kafka offset with the way from KoP 2.8.0.
- Explain why Kafka group cannot be managed via `pulsar-admin`.

[Docs] Fix the wrong implementation documents

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SystemTopicClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java

Fixes #1146
See #1146
1. Add `blockIfQueueFull` when create system producer
2. Add `maxPendingMessages` configuration for system producer. I suggest change the default value from 1000 to 10000, since offset topic's payload is small (less than 200 bytes), it won't take mush memory and could avoid send queue full happen.

add send queue config for system client

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

Currently, the produced message might be disorder, because `topicFuture ` might already done, so we have not queued the produce future.  this future finish might disorder.
See:
https://github.com/streamnative/kop/blob/c03cd9ec2c8da8078b45151f598469b8af4dfb6d/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java#L224-L231
We can add a sleep in `publishMessages` method, it will increase the reproduction probability.
```java
// For control message we don't need to check deduplication.
if (appendInfo.isControlBatch()) {
offsetFuture = publishControlMessage(persistentTopic, byteBuf, numMessages);
} else {
offsetFuture = publishNormalMessage(persistentTopic, byteBuf, appendInfo);
}
try {
TimeUnit.MILLISECONDS.sleep(400);
} catch (InterruptedException e) { …
```

Fix message disorder issue

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Fixes https://github.com/streamnative/kop/issues/1142
Currently, `testConnectListenerNotExist` and `testMultipleListenerName` both use the legacy way to configure multiple listeners. Though KoP still supports the legacy way, see [listeners configuration in branch-2.8.2](https://github.com/streamnative/kop/blob/branch-2.8.2/docs/configuration.md#listeners), the advertised listener in METADATA response is not as expected. We should make it clear in tests.
- Use the correct way to configure multiple listeners in `testConnectListenerNotExist` and verify the brokers cache.
- Rename `testMultipleListenerName` to `testLegacyMultipleListenerName` and emphasize the brokers cache doesn't use the host name in `advertisedListeners`.

Update tests with the correct way to configure multiple listeners

---

pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java

cherry-pick #1176
Bump pulsar to 2.9.2.8 and fix test list offset for empty rollover ledger

Bump pulsar to 2.9.2.8 and fix test list offset for empty rollover ledger

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java

in `kafkaManageSystemNamespaces=false` mode KOP won't create default namespaces, and so you cannot boot the coordinator of "default" namespace. So the KOP protocol handler fails to boot.
Do not try to boot the Coordinator (Group and TX) in case of  `kafkaManageSystemNamespaces=false` mode.
The system administrator will have time to initialise the KOP namespaces after a successful bootstrap of the Pulsar brokers.

Do not boot default coordinators if kafkaManageSystemNamespaces is false

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java

Fixes #1111
refer to #1111 
When there are 3 brokers or more in cluster, one broker may not receive the bundle load and unload event if the bundle is not owned by the broker, in this case the broker will not able to invalidate the look up cache for the topics in this bundle.
We should not cache all topics' look up result, only to cache those topics' look up result which are owned by the broker.
I have checked in my local clusters with 3 brokers.
We need to add the third broker in `DistributedClusterTest` to verify this issue in unit test later.

fix client reconnect fail after bundle unload

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Currently KOP does not follow the configuration set on the Namespace for autoTopicCreation, but only broker.conf
Verify namespace Policies in case of Topic Not Found error, and behave like Pulsar.
This change added tests

Follow namespace configuration for Auto Topic Creation

---

docs/security.md

Fixes https://github.com/streamnative/kop/issues/1183
We should let users know the relationship between KoP's SASL mechanism and Pulsar's authentication provider. In addition, we should make it clear KoP's authentication can be enabled together with Pulsar's authentication.
- Highlight that KoP's SASL mechanisms are based on Pulsar's authentication provider
- Add a section to describe how to enable KoP's authentication and Pulsar's authentication together
- Generate the table of contents for better view via [gh-md-toc](https://github.com/ekalinin/github-markdown-toc)

[Docs] Describe how KoP reuses Pulsar's Authentication provider

---

kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/MemberMetadataTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/TestSSLUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/TestUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DelayAuthorizationFailedCloseTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIdleConnectionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KStreamAggregationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/utils/timer/TimerTaskListTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/utils/timer/TimerTest.java

We should use TestNG instead of JUnit in the KoP units test.
Change all Junit to TestNG

[Test] Change JUnit to TestNG

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Fixes #1211
Currently, when we get offset producer, then the unload happened, the current producer we get might already close, so the commit offset request will fail.
1. When the producer closed, we should return Errors.NOT_COORDINATOR.
2. Add a units test to cover it.

Fix handle offset commit fail when offset producer closed

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java

Support set retention size limit for system/metadata namespace.
* Add config name systemTopicRetentionSizeInMB 
* Add units test to verfiy it.

[Feature] Support set retention size limit for system namespace

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java

Fixes #1225 
Fix  #1225 
When `MessagePublishContext.isMarkerMessage` is true, the pulsar deduplication check will always pass, so we can produce a regular message in KoP when dedup is enabled.
But the isMarkerMessage is not designed for this case, it uses to check the replicator marker. We might need more disscuss.

Allow regular producers with a dedup enabled namespace

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerToken.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerUnsecuredJws.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerUnsecuredValidatorCallbackHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerValidatorCallback.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CustomOAuthBearerCallbackHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java

Currently, when KoP uses the oauth2 authentication, the authorization will fail, because we have customized negotiated properties in `SaslServer` but the oauth2 server is not implemented yet. See: https://github.com/streamnative/kop/blob/b6344dc06ec7b8e4f2e64e43ec1227476f70e8fb/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java#L143-L154
Error log:
```
2022-04-12T02:36:14,551+0000 [pulsar-io-4-1] ERROR io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - error while handle command:
java.lang.NullPointerException: null
at io.streamnative.pulsar.broker.AuthUtils.getToken(AuthUtils.java:29) ~[pulsar-broker-auth-oauth2-2.9.2.7.jar:?]
at io.streamnative.pulsar.broker.authorization.AuthorizationProviderOAuth.isSuperUser(AuthorizationProviderOAuth.java …
```

Fix authorization failed when using oauth2

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java

The 2.8.3 branch's AuthorizationProvider has an abstract method `initialize`, which is changed to the default method in the future. 
We need to implement this method in the 2.8.3 branch to fix the compilation error.
```
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/kop/kop/tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java:[35,8] io.streamnative.pulsar.handlers.kop.security.auth.KafkaMockAuthorizationProvider is not abstract and does not override abstract method initialize(org.apache.pulsar.broker.ServiceConfiguration,org.a …
```

[branch-2.8.3] Fix branch 2.8.3 KafkaMockAuthorizationProvider compilation error

---

docs/configuration.md

The previous PR #1218 has added retention size limit for the system topics, we need to add a doc to explain.

[doc] add set retention size limit for system topic

---

kafka-impl/pom.xml
pom.xml

Currently, the pulsar-broker has a conflict dependency problem. This will cause failure when building the project. And we need to resolve the dependency problem in Pulsar, after Pulsar fixes the problem, we could improve this change.
```
Cannot resolve Could not resolve version conflict among
io.streamnative:pulsar-broker:jar:2.9.2.14 -> io.streamnative:pulsar-zookeeper-utils:jar:2.9.2.14 -> org.apache.bookkeeper:stream-storage-server:jar:4.14.4 -> org.apache.bookkeeper:stream-storage-java-client:jar:4.14.4 -> io.grpc:grpc-core:jar:1.42.1
io.streamnative:pulsar-broker:jar:2.9.2.14 -> io.streamnative:pulsar-zookeeper-utils:jar:2.9.2.14 -> org.apache.bookkeeper:stream-storage-server:jar:4.14.4 -> org.apache.bookkeeper:stream-storage-java-client:jar:4.14.4 -> io.grpc:grpc-testing:jar:1.42.1 …
```

Exclude grpc package from pulsar-broker

---

docs/security.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ServerConfig.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ServerConfigTest.java

Currently, when we use OAuth in KoP, we must set the `kopOauth2ConfigFile`, but most of the time we only use `token` as the validate method. 
We should set the default validate method when `kopOauth2ConfigFile` is not configured.
Set `token` as the default validate method value.

Set default validate method value for OAuth

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

Fixes #769 
Currently, KoP must store group name in zookeeper when KoP handle fetch request because in the current implementation, to monitor consumer stats must have group name when consumer fetch data.
But this data is never deleted in zookeeper. As time goes by, the amount of data becomes larger and larger. Then may cause the cluster crash.
We should find a way to delete this group name when the group is not active.
Delete the group id path when the consumer close.

[Bugfix] Delete group id stored in metadata storage when consumer close

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CustomOAuthBearerCallbackHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthDefaultHandlersTest.java

Currently in KoP tests, the metadata namespace configured by
`kafkaMetadataNamespace` is "default", which is same with the default
namespace of Pulsar and KoP (`kafkaNamespace`).
https://github.com/streamnative/kop/blob/64001937c92d80ed4f652becd8d6b9768918b875/tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java#L176-L177
It's a terrible config because some topic policies might be changed with
the metadata namespace and the offset topic is created during starting.
We should avoid the namespace for normal topics being affected by these
implicit operations.
Remove the configs for `kafkaMetadataTenant` and
`kafkaMetadataNamespace`, then fix the following tests:
- `MultiLedgerTest`: set the infinite retention to avoid rollover
ledgers being removed …

[Tests] Configure a different metadata namespace with the default namespace

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java

Currently, the `SaslPlainTestBase.simpleProduceAndConsume` units test are flaky, see: https://github.com/streamnative/kop/runs/6317175411?check_suite_focus=true#step:12:160
Error log:
```
04:09:22.533 [Thread-8:io.streamnative.pulsar.handlers.kop.storage.PartitionLog@228] ERROR io.streamnative.pulsar.handlers.kop.storage.PartitionLog - Failed to handle produce request for persistent://SaslPlainTest/ns1/topic1-0
java.lang.NullPointerException: null
at io.streamnative.pulsar.handlers.kop.PendingTopicFutures.addListener(PendingTopicFutures.java:74) ~[pulsar-protocol-handler-kafka-2.11.0-SNAPSHOT.jar:?]
at io.streamnative.pulsar.handlers.kop.storage.PartitionLog.appendRecords(PartitionLog.java:226) ~[pulsar-protocol-handler-kafka-2.11.0-SNAPSHOT.jar:?]
at …
```

[bugfix][flaky-test] Fix handle produce request npe

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetadataInitTest.java

Fixes https://github.com/streamnative/kop/issues/1272
https://github.com/streamnative/kop/pull/448 introduced a bug that the
compaction threshold was not set in metadata namespace.
```java
// NOTE: compactionThreshold is always null unless it has been configured
Long compactionThreshold = namespaces.getCompactionThreshold(kafkaMetadataNamespace);
if (compactionThreshold != null && compactionThreshold != MAX_COMPACTION_THRESHOLD) {
// it never gets here unless compaction threshold has been configured
namespaces.setCompactionThreshold(kafkaMetadataNamespace, MAX_COMPACTION_THRESHOLD);
}
```
In addition, currently there is no test that ensures the metadata has
been initialized correctly.
- Configure the compaction threshold when the metadata namespace is
created. Since the policies could …

Fix compaction threshold not configured in metadata namespace

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/DataSketchesOpStatsLogger.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/LocalData.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/ThreadLocalAccessor.java

It's only a code cleanup since static inner classes break the OOP design
and lead to a lot of direct accesses to the private fields and repeated code.
Separate `LocalData` and `ThreadLocalAccessor` from
`DataSketchesOpStatsLogger`. Then use their public methods to access the
private fields.

Separate LocalData and ThreadLocalAccessor from stats logger

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java

Currently, when the `OauthValidatorCallbackHandler#handleCallback` method throws an exception, the client will receive warn log below and it will always try to reconnect.
```
15:51:14.143 [kafka-consumer-2] WARN org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-topic-1-1, groupId=topic-1] Connection to node 782843879 (localhost/127.0.0.1:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
```
Broker side log:
```
2022-05-09T14:29:39,673+0800 [pulsar-io-18-10] ERROR io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Caught error in …
```

Improve handle OAuth callback throw authentication exception behavior

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java

We want to track metrics per tenant, in order to be able to debug and inspect the resource usage by each tenant, and also possibly troubleshot problems.
In case of "authentication enabled" and "kafkaEnableMultiTenantMetadata enabled" when a connection  (a `KafkaRequestHandler`) completes authentication with success, we start pushing metrics with a "tenant=pulsar-tenant" label.
The Tenant is the username used for authentication
TODO (I will add tests when we agree on this feature)
- [x ] `doc-required`

Metrics: expose per-tenant metrics

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java

While investigating on #1281 I have found a couple of enhancements:
- we should add more logging to troubleshoot unknown errors during topic unload
- we can improve some logging
- in case of CursorAlreadyClosedException  we return UNKNOWN_SERVER_ERROR and NOT_LEADER_FOR_PARTITION and this generates a "received an unknown error" log line on the client, that is pretty scary
- improve the toString representation of the callback passed to asyncFindPosition
- return NOT_LEADER_FOR_PARTITION in case of CursorAlreadyClosedException and ManagedLedgerFencedException
- reduce log level of some parts of the code

Clean up errors sent to the client during Topic Unload

---

pom.xml

You cannot use git worktrees in KOP development.
see  https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/215
- [x ] `no-need-doc` 

Add useNativeGit to Git Commit Id Plugin - to support working with worktrees

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java

Fixes https://github.com/streamnative/kop/issues/1295
Currently KoP registers a `InternalProducer` that inherits the broker's
`Producer`  with a unique name for each topic to record the stats so
that REST API. However, when the authoriazion is enabled,
`checkPermissionAsync` will be called on the `InternalProducer` object
when the policies are update in `PersistentTopic#onPoliciesUpdate`.
```java
return cnx.getBrokerService().getAuthorizationService()
.canProduceAsync(topicName, appId, cnx.getAuthenticationData())
```
The code snippet above is from `Producer#checkPermissionAsync`, we can
see the auth role is the `appId` field (`null` in `InternalProducer`'s
constructor) and the authentication data is from the `cnx` field, which
is the `InternalServerCnx` object in KoP. The role and auth …

[Authorization] Remove unexpected produce permission validation

---

ci/hydra/docker-compose.yml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java

Fixes #1261.
Adds a test to make sure when OAuth tokens expire the Kafka client will automatically refresh the token.
Change the Hydra token expiration to 5 seconds, and add a test that sleeps for 5 seconds after getting OAuth tokens, and make sure the Kafka clients still works which means the tokens are refreshed automatically.
- Run the test added which should pass;
- If we change the OAuthBearerTokenImpl class so it returns a lifetimMs that's very far in the future, token refresh is in effect disabled and the test would then fail.
Only adding a test.

Add OAuth token refresh test

---

docs/security.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthBearerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthDefaultHandlersTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthKopHandlersTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionWithOAuthBearerAuthTest.java

The canonical spelling should be `OAuth` (which is also what Kafka uses) instead of `Oauth`.
This changes all the non user facing usages to `OAuth`. Unfortunately to keep backwards compatibility user facing usages can't be changed (maybe we can alias them?).
Doesn't contain user facing changes.

Rename most usages of "Oauth" to "OAuth"

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatterTest.java

#1314
Currently, when we sync produce message in `testChangePulsarEntryFormat` test, this test will fail, but we not find the root cause now, so we just ignore this test first and investigate this issue later.
Ignore test change entry format unit test

[Test] Ignore test change entry format unit test

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java

Currently, the fetch request will fail when we use erlang Kafka-client(`kafka4beam/brod`) to consume the standard message. Because the `kafka4beam/brod` Kafka client always uses `read_commited` to fetch the message even if the client is not using transactions. 
See: https://github.com/kafka4beam/kafka_protocol/blob/713a00e30a5f7ab0d19558c502a7e5cc5b0bfa68/src/kpro_req_lib.erl#L166-L172
```erlang
%% `IsolationLevel = kpro_read_uncommitted' to fetch uncommitted messages.
-spec fetch(vsn(), topic(), partition(), offset(), fetch_opts()) -> req().
fetch(Vsn, Topic, Partition, Offset, Opts) ->
MaxWaitTime = maps:get(max_wait_time, Opts, timer:seconds(1)),
MinBytes = maps:get(min_bytes, Opts, 0),
MaxBytes = maps:get(max_bytes, Opts, 1 bsl 20), %% 1M
IsolationLevel = maps:get(isolation_level, …
```

Fix erlang kafka-client kafka4beam/brod fetch request failed

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatterTest.java

Fixes #1314
In the KoP unit test, the `defaultRetentionSizeInMB` configuration is `0`, so the ledger might get removed when we restart the broker since we are using the non-durable cursor. We should set `defaultRetentionSizeInMB` to `-1` ( -1 is infinite).
Set `defaultRetentionSizeInMB` to `-1` in unit test.

[Test] Fix failed to read all entries after broker restarted

---

docs/reference-metrics.md

The first `Request metrics` section in reference-metrics.md should probably be `Channel metrics` since the metrics are for channels statistics.
Fixed the section name.

Fix metrics description

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KTableTest.java

Master Issue: #1266
#1266 reports that KTable doesn't work for a KoP enabled cluster. It turns out while we have tests for `GlobalKTable` we don't have tests for `KTable`.
Add tests similar to `GlobalKTableTest` but for `KTable`. The tests pass which means #1266 might have been caused by something external to KoP.
- Added KTableTest
Test only

Add tests for KTable

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java

Fixes #1333 #1371 
Currently, the KoP `TransactionCoordinator` and `TransactionStateManager` used two different hash methods for the `partitionFor` method, which will cause serious problems, because the transaction system topic lookup is using the `TransactionCoordinator#partitionFor` and when the transaction init producer ID, it will use another hash method, so the system topic might haven't been immigration yet.
Use the same partition hash method in `TransactionStateManager`.

[Transaction] Fix wrong partition hash method in transaction state manager.

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/DelayedHeartbeat.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/DelayedJoin.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataConstants.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java

Reading through the code in `io.streamnative.pulsar.handlers.kop.coordinator.group` and there are a lot of linting errors. These are annoying and could mask potential bugs, e.g., #1394.
Fix the linter warnings. Most changes should be trivial cleanup, but there is one real bug where `String.format()` is misused.
This change is already covered by existing tests, such as `GroupMetadataTest`.
No client facing functionality changes

Fix linting errors in io.streamnative.pulsar.handlers.kop.coordinator.group 

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java

It seems during the Scala to Java translation some equality checks aren't ported correctly. This could cause potential bugs as demonstrated in the updated tests.
Use `.equals()` instead of `==`.
This change is already covered by existing tests, such as `GroupMetadataTest`.
Minor bug fix

Use `.equals()` instead of `==` for equality checks in GroupMetadata

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java

Fix linting errors and clean up all the things for the files missed in #1393. These warnings also masked #1401 which fixes a bug.
Fix the linter warnings.
No client facing functionality changes

Fix linter warnings in GroupMetadataManager and GroupCoordinator

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java

The `LengthFieldPrepender` is a sharable handler, so we can make it singleton to avoid too many objects created.
Make the LengthFieldPrepender singleton

[improve] Make the LengthFieldPrepender singleton

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelInitializer.java

The `LengthFieldPrepender` is a sharable handler, so we can make it singleton to avoid too many objects created.
Make the LengthFieldPrepender singleton

[improve] Make TransactionMarkerChannelInitializer LengthFieldPrepender singleton

---

pom.xml

KoP branch-2.10.1 cannot be compiled with JDK 17.
> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kafka-client-api: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @46d148bd
It's because lombok 1.18.4 is not compatible with JDK 17. There is no problem in master branch because https://github.com/streamnative/kop/pull/1303 has upgraded lombok to 1.18.22.
Upgrade the lombok version to 1.18.22. …

Upgrade lombok to make KoP compatible with JDK 17

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java

Fixes #1412
See https://github.com/streamnative/kop/issues/1412#issuecomment-1189337496
The early return in a for loop of
`TransactionMarkerRequestCompletionHandler#onComplete` could break the
loop so that the left `TxnIdAndMarkerEntry` objects cannot be processed.
To avoid wrong usage of `return` in a loop, use `Iterable#forEach`
instead of a range for loop  so that a `return` clause won't break the
whole for loop.

Fix transaction state update could be skipped for multiple transaction commits

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManagerTest.java

Using the admin API to check if the "topic" exists is a heavy operation, we should use the metadata cache to check if the topic exists.
Check the topic exists from cache

[improve] Check the topic exists from cache

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManagerTest.java

Fixes #1386 
Since the transaction operation will write into the transaction log first, 
the marker will write after the response to the client, 
however, when we commit the transaction and delete the topic Immediately, 
the marker write operation will always fail, 
so the write operation will always retry.
We need to check the topic exists when we try to write the marker.
* Add some debug log for writing marker log.
* Reusing publish message method.
* Add unit test for `TransactionMarkerChannelManager `.

[Transaction][branch-2.8.3] Fix endless writing txn marker requests when the topic is deleted

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusMetricsProvider.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java

Master Issue: https://github.com/streamnative/kop/issues/1368
*Add cluster label in kop metrics to identify different pulsar clusters.*
*Get cluster name config from `KafkaServiceConfigurtion` and put into the root of `PrometheusStatsLogger`'s default labels.*
No new config item is introduced

[Metrics] add cluster label to all kop metrics in Prometheus status logger

---

.github/workflows/pr-tests.yml

Fixes #1361
We don't need to waste time verifying the previous commit.
See:
https://github.com/apache/pulsar/blob/b2146fd51d1934a18083e8469e9d50946097fefd/.github/workflows/pulsar-ci.yaml#L29-L31

[CI] Cancel previous CI workflow if new commit pushed

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java

We have record add latency when publishing complete, but the latency unit is wrong, we should use `TimeUnit.NANOSECONDS` instead of `TimeUnit. MICROSECONDS`.
Use `TimeUnit.NANOSECONDS` instead of `TimeUnit. MICROSECONDS`.

[Bugfix] Fix incorrect publish latency unit

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java

Fixes: #1424
When the KoP handled the end transaction request, it returned the `UNKNOWN_SERVER_ERROR` error.
I can't reproduce this in Flink Jobs, but when I review the end transaction code, it is possible to be caused by the produce epoch fence since we are using the `UNKNOWN_SERVER_ERROR` error as the produce epoch fence error.
However, in Kafka, when the produce epoch fence, it will return an `INVALID_PRODUCER_EPOCH` error, we should keep it the same.
Error log:
```
2022-08-05T08:37:26,952+0000 [pulsar-ph-kafka-64-30] ERROR io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionCoordinator - Aborting append of COMMIT to transaction log with coordinator and returning UNKNOWN_SERVER_ERROR error to client for Source: Custom Source -> Sink: …
```

[Transaction] Return INVALID_PRODUCER_EPOCH error when the transaction produces epoch fence happened

---

pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java

There are two errors will happen when we use JDK 17 to run the KoP unit test:
1. listener `'PLAINTEXT://192.168.0.1/<unresolved>:15007'` is invalid
```
org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: listener 'PLAINTEXT://192.168.0.1/<unresolved>:15007' is invalid
at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:824)
at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:368)
at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:359)
at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.internalSetup(KopProtocolHandlerTestBase.java:298)
at …
```

[Test] Fix unit test in JDK 17 env

---

docs/reference-metrics.md

Fixes #1459
* The KoP metrics are exposed at port `8080`, not `8000`. However, the document shows `8000`.
* Change the port from `8000` to `8080` in docs/reference-metrics.md
* To access the document docs/reference-metrics.md and you can find `8080` port.
Please refer to docs/reference-metrics.md
Please refer to docs/reference-metrics.md
Please refer to docs/reference-metrics.md

[Docs] - The KoP metrics are exposed at port 8080, not 8000

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderWithDisableGroupLevelConsumerMetricsTest.java

The group-level consumer metrics are heavyweight metrics, 
they use the ZK node to store the group id, 
and read it when fetching one partition is completed,
we should add an option to disable the group-level consumer metrics.
* Add an option to disable the group-level consumer metrics.
* Add unit test to cover disable case.
- [] `no-need-doc` 

[feature] Support disable group-level consumer metrics

---

.github/workflows/pr-tests.yml
kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ProduceContext.java
pom.xml

When deploying KoP into Maven central with Java 11, it failed when building JavaDocs:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project kafka-client-api: MavenReportException: Error while generating Javadoc: 
Error:  Exit code: 1 - /home/runner/work/streamnative-ci/streamnative-ci/kop/kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Producer.java:25: error: cannot find symbol
Error:      default ProduceContext.ProduceContextBuilder<K, V> newContextBuilder(String topic, V value) {
Error:                            ^
Error:    symbol:   class ProduceContextBuilder
Error:    location: class ProduceContext
Error:  /home/runner/work/streamnative-ci/streamnative-ci/kop/kafka-client-api/src/main/java/io/streamna …
```

Avoid lombok usages in interfaces for JavaDoc plugin

---

docs/configuration.md

1. The current example uses double quotes, which can mislead users into imitating the configuration. But you can't use quotation marks. The update uses backquote and configures the complete example, which may be expressed more clearly.
2. The last less than sign will have a markdown syntax exception, now adjust.

Update the description of kopAllowedNamespaces

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java

Fixes #1458
When we use the pulsar entry formatter and enable replicated subscription, 
the pulsar broker will write the replicated subscription marker,
but when we handle this marker, we will treat this marker as a transaction marker.
However the replicated subscription marker doesn't have `txnid_most_bits`,
so we will get the following exception, and the consumer will never receive the message.
```
2022-08-31T14:47:09,567+0800 [pulsar-2-5] ERROR io.streamnative.pulsar.handlers.kop.MessageFetchContext - Request RequestHeader(apiKey=FETCH, apiVersion=2, clientId=consumer-5, correlationId=246712): Partition test-topic read entry exceptionally. 
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Field 'txnid_most_bits' is not set
at …
```

[fix] Handle replicated subscription marker correct in pulsar entry formatter

---

pom.xml

snakeyaml < 1.31 is subject to CVE-2022-25857
Upgrade to 1.31

[security] Upgrade snakeyaml to 1.31

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java

There is some flaky test when we stop the brokers.
```
Error:  Failures: 
Error:    CacheInvalidatorTest.cleanup:111->KopProtocolHandlerTestBase.internalCleanup:319->KopProtocolHandlerTestBase.stopBroker:355->KopProtocolHandlerTestBase.stopBroker:351 » PulsarServer
Error:    TransactionWithOAuthBearerAuthTest.cleanup:72->TransactionTest.cleanup:77->KopProtocolHandlerTestBase.internalCleanup:319->KopProtocolHandlerTestBase.stopBroker:355->KopProtocolHandlerTestBase.stopBroker:351 » PulsarServer
```
The root cause is when we close the `TransactionMarkerChannelManager`, 
we will traverse all entries of `handlerMap`, 
but some of the entry already been removed, 
we can use `ConcurrentHashMap` to avoid it.
Use `ConcurrentHashMap` instead of `HashMap`. …

[Transaction] Fix concurrent modification exception when broker close

---

.github/workflows/pr-tests.yml
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Upgrade `maven-shaded-plugin` to 3.4.0 because 3.2.4 seems not work with JDK 17.
> entry io/streamnative/kafka/client/zero/nine/Consumer009Impl.class: java.lang.IllegalArgumentException: Unsupported
Skip `__change_event` system topic when processing list topics request.

Bump Pulsar to 2.11.0.0-rc3 and use JDK17 for KoP

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java

Fixes #1500 
The baseOffset is not monotonically increasing, consumer cannot submit offset correctly.
When the offset is submitted, the increasing judgment mode of baseOffset is changed
This change is already covered by existing tests.
1.passed GroupMetadataManagerTest
2.passed GroupMetadataTest

[BUG#1500] Cannot submit offset correctly

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java

Fixes #1502
Currently the `partitioner` in `GroupMetadataManager` can be customized
but it's only for test. The reason is that when
`testRequestHandlingWhileLoadingInProgress` was migrated from Kafka
source code, there is something wrong:
1. `otherGroupId` should be tested while it's actually `groupId`.
2. `otherGroupId` should be "myGroup", not "myGroupId", which cause the
error of hash code.
Therefore, a customized partitioner is used in `GroupCoordinatorTest`.
In addition, after https://github.com/apache/kafka/pull/9441, the
partition of a group id won't be put into `loadPartitions` if it already
exists in `ownedPartitions`.
- Don't add partition into `loadPartitions` when it exists in
`ownedPartitions`.
- Use the fixed partitioner to calculate the partition of a group id.
Though the …

[refactor][group] Simplify code and optimize loading partitions management

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

We don't get the topic name when topic failed to found
```
2-09-16 14:12:30.043 [AsyncHttpClient-62-1] ERROR io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - [[id: 0xb930401b, L:/x:9093 - R:/x:46344]] Automatic topic creation is not allowed on namespace public/data-channel
```
Log name of topic when topic not found

Log name of topic when topic not found

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpRequestProcessor.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/package-info.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/MigrationHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/MigrationManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/package-info.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/http/HttpRequestProcessorTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/migration/MigrationManagerTest.java

Master Issue: #1475
The migration service needs a set of API for the clients to talk to.
This adds the HTTP request handling boilerplate for the new live migration service. Note this is largely based on the Schema Registry HTTP handling code and listens to a separate port from the main Kafka listener, and in the future we should probably refactor the Schema Registry code to using this common boilerplate.
The migration service is WIP so no tests are written yet but we can make sure the endpoint works by visiting it.
Doesn't need docs at this moment, will add doc after the live migration service is done.

Add migration handler

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java

Fixes #1444 #1168
Currently, the list offset operation might return the wrong offset.
Because when `position > lac`, we will try to get the latest offset from `AppendIndexMetadataInterceptor`,
However, if we have a producer produce messages to the current `ManagedLedger`,
the latest offset might be wrong since the `AppendIndexMetadataInterceptor#index` is increased before the ledger persistence.
When this case happens, we might lose the first few pieces of messages, since the Kafka client will reset offset in the beginning.
Make the `position > lac` condition return offset 0.

Fix list offsets response wrong result

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpRequestProcessor.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/package-info.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/MigrationHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/MigrationManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/package-info.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/http/HttpRequestProcessorTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/migration/MigrationManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java

Master Issue: #1475 
The migration service needs a set of API for the clients to talk to.
Also, there are a lot of code style warnings for these files in IntelliJ which makes it harder to find real issues.
This adds the HTTP request handling boilerplate for the new live migration service. Note this is largely based on the Schema Registry HTTP handling code and listens to a separate port from the main Kafka listener, and in the future we should probably refactor the Schema Registry code to using this common boilerplate. Also contains some IntelliJ auto code style fixes.
Doesn't need docs at this moment, will add doc after the live migration service is done.

Add migration handler and various code style fixes

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicLookupService.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/metadata/ManagedLedgerPropertiesMigrationMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/metadata/MigrationMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/metadata/MigrationMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/metadata/MigrationStatus.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/metadata/package-info.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/migration/metadata/ManagedLedgerPropertiesMetadataManagerTest.java

Master Issue: #1475 
The migration workflow and metadata management is somewhat complicated, so it's probably cleaner to group the corresponding logic together. This will be used by later PRs.
This add a MigrationMetadataManager interface and a concrete implementation using managed ledger properties. It's not 100% complete yet and will be filled out in subsequent PRs.
WIP
Only contains internal business logic

Add MigrationMetadataManager

---

oauth-client/pom.xml
pom.xml

`jackson-databind`  2.13.4 is vulnerable to [CVE-2022-42003](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-42003)
* Upgrade to 2.13.4.1

[fix][sec] Upgrade JacksonXML to 2.13.4.1 to get rid of CVE-2022-42003

---

pom.xml

Current protobuf version imported by the broker is vulnerable, see related Pulsar patch: https://github.com/apache/pulsar/pull/18086
* Add bom import to 3.19.6

[fix][sec] Upgrade protobuf-java to 3.19.6

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdvertisedListener.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/AdvertisedListenerTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/EndPointTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java

Fixes #1567
See: #1567
* Refactor the advertised listener parser to `AdvertisedListener` class.
* Return full IPv6 address when advertised listeners are using simplified IPv6 address.
* Add units test to cover the `AdvertisedListener` class.

Fix lookup error when use simplified IPv6 address

---

.github/workflows/pr-tests.yml
kafka-impl/pom.xml
pom.xml

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pulsar-protocol-handler-kafka: Compilation failure
Error:  /home/runner/work/kop/kop/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdvertisedListener.java:[23,45] package org.apache.commons.validator.routines does not exist
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, …
```

[branch-2.10.2] Add commons-validator dependency

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/NamespaceBundleOwnershipListenerImpl.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TenantContextManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

Currently, the `PartitionLog` object from `PartitionLogManager` is never removed, even if the topic has been unloaded. Also, if the topic is removed, the object of `PartitionLog` will still in the memory.
* Remove the `PartitionLog` object from `PartitionLogManager`.
* Delete useless `ReplicaManager` by tenant map.

[improve] Remove partition log when bundle unload

---

codecov.yml

It's hard to do a code review when there are many CodeCov annotations on the page, and It doesn't help much. So let's disable it.

Disable CodeCov annotation check in code review

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java

This is a trivial fix. The `getTlsCertificateFilePath` is meant to be the tls certificate chain when sending to a peer, and the `getTlsTrustCertsFilePath` is meant to be the root CAs.
This PR could technically break installations. I'm unsure how we'd like to handle backwards compatibility here.
Note that this PR is the same as https://github.com/apache/pulsar/pull/18712.
* Fix an incorrect reference to trusted certificates.
This is a trivial change.
No docs are required, but a release note might be helpful for some users.

[fix] Use correct path for pulsar client TlsTrustCertsFilePath

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java

The `TransactionMarkerChannelManager#addTxnMarkersToBrokerQueue` method modifies an `ArrayList` from callbacks on futures, which could result in unsafe modification of the list.
* Replace `ArrayList` with `CopyOnWriteArrayList`. I chose `CopyOnWriteArrayList` since it is simple and the expected number of writes to the list is low.
This is a simple fix.

[fix] Use thread-safe list in TransactionMarkerChannelManager

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java

When you run transaction the broker is full of useless logs
Reduce the log level on the transactions hot path

Transactions - reduce log level

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java

Fixes #1542
The `MultiLedgerTest.testListOffsetForEmptyRolloverLedger` method is flaky, 
but the root cause is hard to find, it may be caused by short timeout, 
we can add more timeout to check the ledger's size.
* Increase timeout to check the ledger's size.
* Add more logs to get more context when the flaky test happens again.

[flaky-test] Fix MultiLedgerTest.testListOffsetForEmptyRolloverLedger flaky test

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/AppendRecordsContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishThrottlingTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/PreciselyMessagePublishThrottlingTest.java

Currently, KoP doesn't support publish rate limit, but it is a helpful feature for users,
In this PR, it introduced the message publish rate limit, and the rate limit is reused from
Pulsar, it can work with Pulsar together.
* Support message publish rate limit.
* Added units test to verify it.
Need check if the KoP needs to support this KIP: https://cwiki.apache.org/confluence/display/KAFKA/KIP-219+-+Improve+quota+communication

[feature] Support message publish rate limiting

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerImpl.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerImplTest.java

The `ProducerIdManagerImpl` updates `currentProducerIdBlock` and `nextProducerId` from callbacks that are likely run on separate threads. When many producers connect, that could lead to data races that might lead to incorrect incrementing for producer ids. This PR seeks to ensure that getting the next `currentProducerIdBlock` is thread safe and does not get run concurrently, and to make sure that updates to `nextProducerId` are always thread safe. My model relies on synchronizing on the object, which is already partially implemented with synchronized methods.
* Update the callback in `generateProducerId` to ensure that `nextProducerId` is updated safely and `currentProducerIdBlock` is read safely
* Update `getNewProducerIdBlock` so that the `currentProducerIdBlock` is only updated after a …

[fix] Make ProducerIdManagerImpl thread safe

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

There is currently a memory leak in the `handleFetchRequest` logic. This PR fixes that leak.
Steps to observe a memory leak:
1. Connect consumer.
2. Send fetch request to broker, which creates a callback: https://github.com/streamnative/kop/blob/66efad61c853aa9044fd4b03e7bffc3823a36042/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java#L243
3. Close connection to broker before the callback completes, which triggers the logic to complete all uncompleted futures: https://github.com/streamnative/kop/blob/66efad61c853aa9044fd4b03e7bffc3823a36042/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java#L113-L120
Credit to @eolivelli for identifying that the close logic was leading to a memory leak.
Note: this code contains the …

[fix] Recycle fetchRequest records when resultFuture already complete

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java

When entries are filtered out in the `PartitionLog#getCommittedEntries` method, they are not released, which is a leak.
Here is the relevant stack trace from netty indicating there is an issue in the `handleEntries` method:
```
2022-12-12T17:51:34,277+0000 [pulsar-io-4-26] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before
it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
io.netty.buffer.AdvancedLeakAwareByteBuf.nioBuffer(AdvancedLeakAwareByteBuf.java:713)
io.streamnative.pulsar.handlers.kop.utils.ByteBufUtils.getNioBuffer(ByteBufUtils.java:96)
io.streamnative.pulsar.handlers.kop.format.AbstractEntryFormatter.decodeSync(AbstractEntryFormatter.java:232) …
```

[fix] Release leaked entries in getCommittedEntries

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

With the upgrade to Kafka 2.8.x we introduced a regression in the handleProduceRequest method, we are not counting
correctly the number of partitions.
If the client sends data for more than one partition for the same topic, then the result is a REQUEST_TIMED_OUT because we are calling "completeOne.run()" once per partition, but we are using the number of topics as the expected number of "completeOne" calls.
Count correctly the number of partitions.

[bugfix] Fix regression with the upgrade to 2.8.x: Count corrently the number of partitions in ProduceRequest

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KStreamAggregationTest.java

`KStreamAggregationTest` uses a Scala class `ConsoleConsumer`, which might lead to a `NoClassDefFoundError` in branch-2.10: https://github.com/streamnative/kop/actions/runs/3797937683/jobs/6459789362
Replace the `ConsoleConsumer` use with a `KafkaConsumer` and the same formatting logic on each received record.

Remove usage of Scala classes from Kafka in tests

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusStatsLogger.java

Fixes https://github.com/streamnative/kop/issues/1652
Pulsar 2.10 or earlier depends on io.prometheus:simpleclient:0.5.0, whose implementation of `Collectors.sanitizeMetricName` uses regex, which is inefficient and costs much CPU.
Migrate the implementation of `sanitizeMetricName` from io:prometheus:simpleclient:0.16.0 to branch-2.10 or earlier.

[branch-2.10] Use a more efficient implementation of sanitizeMetricName

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java

We are using `NioEventLoop` instead of `Epoll`. It is recommended to use `Epoll`: https://netty.io/wiki/native-transports.html.
* Use the Apache Pulsar method `EventLoopUtil#newEventLoopGroup` to load the best event loop. Instead of adding any configuration, I am simply using the defaults that we've already relied on. Please let me know if we want to make it configurable. Note that 0 threads defaults to 2 times the number of available processors.
This change is trivial, and since the broker already uses this method to create the event loop, it should be low risk. The only down side is that Apache Pulsar could move this method and break our usage.
This is an internal improvement.

[improve] Transactions: use Epoll for eventLoopGroup when available

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

When a connection is closed while having pending requests, the ByteBuf is not released.
Release the ByteBuf attached to the original request

[bugfix] Fix memory leak in case of closed connections with pending requests

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusTextFormatUtil.java

There is some unnecessary boxing of `boolean` primitives in the code. This PR removes that boxing.
* Replace `Boolean` with `boolean` when appropriate.
No new tests are added, but the changes are pretty minor and are easy to understand. In all cases, we can see that the calling methods and the usage of the variables expect a primitive `boolean`.

Remove unnecessary Boolean boxing

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusStatsLogger.java

- reduce unnecessary garbage created by adding some caching
This came up in some profiling

Optimize performance of EncodeResult.updateProducerStats and DecodeResult.updateConsumerStats

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java

With the upgrade of the Kafka clients to 2.8.x we introduced a performance regression
Remove the fixed 10ms delay

[performance] Remove dummy 10ms throttling on FetchResponse

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

There is no need to use a static Map to access the LookupClient.
Keep only a reference to the field in the ProtocolHandler and pass it.
This way the lifecycle is cleaner.
Also we close all the "clients" as last step, otherwise other components may see unexpected errors due to the clients being shutdown.

[cleanup] Remove static LOOKUP_CLIENT_MAP

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingTopicFutures.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java

Fixes https://github.com/streamnative/kop/issues/1629 
This is a backport of this patch in S4K (Starlight for Kafka)
https://github.com/datastax/starlight-for-kafka/pull/58 
There is a race condition when two threads try to access the same topic.
Fix the handling of concurrency in PendingTopicFutures.
Fix the KafkaMessageOrderTestBase
This change is already covered by existing tests and added new tests

[bugfix] Fix NPE in PendingTopicFutures and fix KafkaMessageOrderTestBase

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java

Sometimes tests hang during teardown  because the shutdown procedure of the broker is blocked in waiting for our PulsarClients to close.
Wait for some time.
I have filed this issue upstream in Pulsar in order to have a better management of this problem
https://github.com/apache/pulsar/issues/19579

[tests] Prevent test timeouts due to pulsar client hanging while shutdown

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PulsarStorageProducerIdManagerImplTest.java

https://github.com/apache/pulsar/pull/17696 removes the
`powermock-reflect` dependency, which leads to a compilation error in
KoP.
Upgrade the Pulsar dependency to 2.11.0.0-rc5. Then replace
`Whitebox.invokeMethod` with `MethodUtils.invokeMethod`.
It also fixes the bug that null values are not handled well for
non-batched messages. This bug was exposed because of
[PIP-189](https://github.com/apache/pulsar/pull/16605).
Migrate the bug fix for non-batched messages to branch-2.10.x and
branch-2.9.x.

Fix the compatibility issue with Pulsar 2.11.0

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManagerSharedState.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopEventManagerTest.java

Currently KafkaTopicManagerSharedState contains a cache of PersistentTopic references that is useless and makes the code harder to understand. It is also possible that sometimes we fail to remove the references to the Producer registered on the PersistentTopic.
Clean up the code and do not cache the "topics". From the Producer we can have the reference to the topic and also we can use the KafkaRequestHandler as cache key.
With this change we are going to create one Producer per KafkaRequestHandler, this also allows to track correctly the number of producers and the IP addreses.
(If this PR contains …

[improvement] Do not cache topics in KafkaTopicManagerSharedState

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/AbstractEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterFactory.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServerTest.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandlerTest.java

- Upgrade the Pulsar dependency to 3.0.0.1-SNAPSHOT
- Use `List<EntryFilter>` from https://github.com/apache/pulsar/pull/19364 as the filters
- Remove the removed APIs in `AuthorizationService`
- Use `TopicType` instead of String.
- Fix SaslAuthenticator failure caused by https://github.com/apache/pulsar/pull/19295

Fix the incompatibility with Pulsar 3.0.0.1-SNAPSHOT

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java

After upgrading the Kafka client library to 2.8.x some clients, like the KSQLDB server, require that describeCluster API is implemented.
- implement describeCluster
- response with UnsupportedVersionException to unknown APIs
This change added tests
No need to add docs, this is a standard API

[ksqldb] Add implementation for describeCluster

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
pom.xml
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottleTestBase.java
tests/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

MessagePublishBufferThrottleTestBase sometimes fails on my CI
- Upgrade Mockito
- Use MockStatic in order to precisely intercept the pausing/resuming of connections
- Update the test

[tests] Unflaky MessagePublishBufferThrottleTestBase

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Some of the Producer requires the `message.max.bytes` configuration.
```
Error: [CDC:ErrKafkaNewSaramaProducer]new sarama producer: [CDC:ErrKafkaBrokerConfigNotFound]cannot find the `message.max.bytes` from the broker's configuration
```
* Add `message.max.bytes` for describe broker config. The config is reused pulsar config.

[improve] Add message.max.bytes for describe broker config

---

docs/security.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java

Currently, when authentication is enabled, we have to pass `token:<token>` as the password in the `basic.auth.user.info` config. However, some clients don't allow a colon appearing in the password.
See
https://github.com/confluentinc/confluent-kafka-python/blob/f3055be4d2aa18ffc833cc88f7b08b173d4da433/src/confluent_kafka/schema_registry/schema_registry_client.py#L108-L111
- Support passing the token directly, i.e. without the "token:" prefix, as the password
- Add the document to describe how to configure the authentication for Schema Registry

Support passing the token directly as the password for Schema Registry

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/ErrorMessage.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/HttpJsonRequestProcessor.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/HttpRequestProcessor.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/model/impl/SchemaStorageException.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/AbstractResource.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SubjectResource.java
schema-registry/src/test/java/io/streamnative/pulsar/handlers/kop/schemaregistry/SchemaRegistryHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java

Sometimes when a schema REST request failed, `buildErrorResponse` might be called and a HTTP response whose content type is `text/plain` will be sent to the client. However, Confluent's Schema Registry client expects the response content is a JSON representation of `ErrorMessage` class:
```java
ErrorMessage errorMessage;
try {
errorMessage = (ErrorMessage)jsonDeserializer.readValue(es, ErrorMessage.class);
} catch (JsonProcessingException e) {
errorMessage = new ErrorMessage(JSON_PARSE_ERROR_CODE, e.getMessage());
}
```
https://github.com/confluentinc/schema-registry/blob/7bc2a042f794416f28f2e79598a6abb972243741/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java#L199
For example, when a 404 Not Found error is returned, the error message at client side …

[fix][schema] Return JSON error message for failed request

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAdminTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

Please don't use the admin APIs, and it is hard to support in KoP.
| Method                       | Is Support                                     |
|------------------------------|-------------------------------------------------|
| createAcls                   | Don't support, use pulsar admin to manage acl. |
| deleteAcls                   | Don't support, use pulsar admin to manage acl. |
| describeAcls                 | Don't support, use pulsar admin to manage acl. |
| listAcls                     | Don't support, use pulsar admin to manage acl. |
| electLeaders                 | Don't support, it depends on the pulsar.       |
| describeUserScramCredentials | Don't support                                  |
| alterUserScramCredentials    | Don't support …

[test] Add kafka admin api unit test

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicAndMetadata.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

https://github.com/apache/kafka/blob/61530d68ce83467de6190a52da37b3c0af84f0ef/core/src/main/scala/kafka/server/KafkaApis.scala#L1203-L1210
When a topic is not found, Kafka only returns `INVALID_TOPIC_EXCEPTION` when the topic name is invalid. If the topic name is valid, `UNKNOWN_TOPIC_OR_PARTITION` will be returned.
- Refactor `getPartitionedTopicMetadataAsync` to return the correct error code (and rename this method). For the case when any error happens at the broker side, return `UNKNOWN_TOPIC_OR_PARTITION`.
- Do not print error logs when the topic is not found. Kafka also does not print the logs. The Kafka client will print the logs for `UNKNOWN_TOPIC_OR_PARTITION`.
- Add `testTopicMetadataNotFound` to verify the changes.
(If you need help on …

Return a correct metadata response when topic is not found

---

pom.xml
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/HttpJsonRequestProcessor.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java

[Schema] Return 401 error when no HTTP authentication is configured
When authentication is enabled, if the Schema REST requests were sent without HTTP authentication header, the Schema Registry will return 404, rather than 401.
- When `SchemaStorageException` is thrown, build the response with the error code and the exception message.
- Add `testSchemaNoAuth` to verify 401 unauthorized will be returned.

[Schema] Return 401 error when no HTTP authentication is configured

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/model/impl/PulsarSchemaStorage.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRestApiTest.java

When I tried to delete a subject, the subject could still be queried even after I restarted the broker.
```bash
$ curl -L http://localhost:8001/subjects
[ test ]
$ curl -X DELETE -L http://localhost:8001/subjects/test
$ curl -L http://localhost:8001/subjects
[ test ]
```
The reason is that the `SchemaStatus.DELETED` is never processed.
In `PulsarSchemaStorage#applyOpToLocalMemory`, when the status is `DELETED`, remove the entry with the same schema id from the `schemas` cache.
Add `SchemaRestApiTest#testDeleteSubject` to verify this change. To verify modifications also work after the restart, expose the schema storage for tests and add `resetSchemaStorage` to clear the storage.
(Please …

[Schema Registry] Fix the delete operation not work

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/LongAdderCounter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/NullStatsLogger.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java

There was an API change in `org.apache.bookkeeper.stats.Counter`, which made the build failed for 3.0.0.1-rc1.
Upgrade the dependency and use the new API.

Upgrade the Pulsar version to 3.0.0.1-rc1

---

schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/model/Schema.java
schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SubjectResource.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRestApiTest.java

The response is wrong when querying schema by subject and version.
Here is an example response of Confluent Schema Registry:
```json
{
"subject":"test-value",
"version":1,
"id":1,
"schema":"{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.example\",\"fields\":[{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"age\",\"type\":\"int\"}]}"
}
```
Here is the corresponding response of KoP:
```json
{
"id" : 1,
"schema" :
"{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.example\",\"fields\":[{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"age\",\"type\":\"int\"}]}",
"subject" : "test-value",
"version" : 1,
"type" : "AVRO"
}
```
KoP has an extra "type" field, for some old versions of `KafkaAvroSerializer`, they would fail to parse the response.
- …

[Schema] Fix wrong response when querying schema by subject and version

---

pom.xml

Kop uses some jdk8+ grammar which is not supported by Javadoc plugin source 8 configuration when the version is 2.11+, so we need to upgrade it.

Fix javadoc plugin configuration version

---

pom.xml

org.json:json@20201115 - https://www.cve.org/CVERecord?id=CVE-2022-45688
Upgraded to org.json:json@20230227
com.charleskorn.kaml:kaml@0.20.0 - https://www.cve.org/CVERecord?id=CVE-2023-28118
Upgraded to com.charleskorn.kaml:kaml@0.53.0
Also fixed kotlin and kotlinx version to the same version: kotlinx: 1.5.0 and kotlin 1.8.10 (the version used by kotlinx)

Upgrade org.json and kaml to non vulnerable versions

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/PulsarMessageBuilder.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java

When using pulsar entry formatter and publishing zero timestamp record will cause request timeout,
the root cause is we will set the event time when timestamp >= 0, but the event time has a check to ensure time > 0.
See:
```java
public PulsarMessageBuilder eventTime(long timestamp) {
checkArgument(timestamp > 0, "Invalid timestamp : '%s'", timestamp);
metadata.setEventTime(timestamp);
return this;
}
```
* Do not check the event time before setting the event time.
* Add test to verify this issue.
*(Please pick either of the following options)*
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
*(example:)*
- *Added …

Fix pulsar entry formatter encode zero timestamp record caused exception

---

docker-compose-cluster.yaml
docker-compose.yml

Currently, the KoP supports schema registry and transaction, 
But this feature is not enabled in the standalone and cluster docker-compose by default.
* Enable transaction and schema registry on docker-compose yaml.
* Upgrade the docker-compose sn-pulsar version to 2.11.0.5.

[improve] Enable transaction and schema registry on docker compose

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetResetTest.java

[fix][branch-2.10.4] Unify fetch offset topic name

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java

The `createPulsarClient` method is meant to model the PulsarServer method named `getClient`. However, it uses a different config to determine when to enable TLS. This leads to divergent behavior within the broker. Here is the pulsar code:
https://github.com/apache/pulsar/blob/092819b5c4a68dbc39d9a650d5370af9455e805d/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L1554-L1555
* Replace `isTlsEnabled` with `isBrokerClientTlsEnabled` when creating pulsar client

Use brokerClientTlsEnabled to configure pulsar client

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaNonPartitionedTopicTest.java

Fix: #1852
When the topic has an active producer or consumer, then we are not able to delete the topic by using `admin.topics().delete(topic)`, we should force delete it.
Use the force option to delete the topic in the test.

Fix flaky-test: KafkaNonPartitionedTopicTest.testNonPartitionedTopic

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java

Currently, the consumer can read unstable messages in `read_committed` mode.
1. If the fetch offset is equal to or greater than LSO(last stable offset), skip reading entries to avoid useless reading.
2. If the entires' offset is equal to or greater than LSO, discard them to avoid sending them to the consumer.
Add a new unit to verify consumers can't receive unstable messages.

[fix] Fix read unstable messages

---

schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SchemaResource.java
schema-registry/src/test/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SchemaResourceTest.java

See: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--schemas-ids-int-%20id-schema
And the PR also fixed the missed schema type for "GET /schemas/ids/{int: id}"
https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--schemas-ids-int-%20id

[feat][schema] Support getting schema string by id

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java

Prevent ConcurrentModificationException in getProducer()

[bugfix][transactions] Prevent ConcurrentModificationException in getProducer()

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java

The kop consumer's cursor is maintained only in the kop and does not need to be deleted in the pulsar topic
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*
Fixes #<xyz>
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*
Master Issue: #<xyz>
when consumer is closed, there is a warn in kop logs:
kop create a nonpersistent cursor for each partitioned-topic  of each consumer group.  This cursor is not committed to topic.getManagedledger (), so when the consumer closes, topic.getManagedLedger().asyncDeleteCursor() is not required
*(Please pick either of the following options)*
*(or)*
This change is already covered by existing tests, such as …

fix: remove topic.getManagedLedger().asyncDeleteCursor

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java

https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/coordinator/transaction/TransactionMetadata.scala#L190
The `TxnTransitMetadata.topicPartitions` should be immutable, otherwise it will cause race conditions.
Make TxnTransitMetadata.topicPartitions immutable

[bugfix][transactions] Make TxnTransitMetadata.topicPartitions immutable

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java

Release memory in TransactionMarkerChannelHandler

[bugfix][transactions] Release memory in TransactionMarkerChannelHandler

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java

Get size from byteBuf earlier to prevent unnecessary retention

[improve] Get size from byteBuf earlier to prevent unnecessary retention

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java

When using pulsar format and has messages In batch, 
we should use single message metadata's event time as the record timestamp.
Use single message metadata's event time as the record timestamp

[bugfix] Fix decode pulsar format batch records timestamp

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java

(cherry picked from commit 38d30be17d3582d5382ef3c1596a5d83254006f8)
TransactionMarkerRequestCompletionHandler retries on UNKNOWN_SERVER_ERROR.

[fix][transaction] TransactionMarkerRequestCompletionHandler retries on UNKNOWN_SERVER_ERROR

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/PulsarMessageBuilder.java

This PR is used to cherry-pick these commits.
https://github.com/datastax/starlight-for-kafka/commit/760f213c2c78156138a9e5cb9a93b43b29090655
https://github.com/datastax/starlight-for-kafka/commit/f7f6b7f47329d247446567984cd8c8651fd84ffa
https://github.com/datastax/starlight-for-kafka/commit/2c7c24ef54520cd753fe1ad5e347924ab50dfdcd
https://github.com/datastax/starlight-for-kafka/commit/76c386c1499e3fda8cf0e2b26cdfbeb7f181e6f0
1. Optimize encoding by reducing context switching.
2. Don't copy the value to a byte[] while formatting in Pulsar format.
3. Do not perform an additional memory copy

[perf][improvement] Improvements for PulsarEntryFormatter

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SystemTopicClient.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopic.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataConstants.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/package-info.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/CoreUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopicTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java

Currently the offset topic I/O operations are deeply coupled with GroupMetadataManager so that the code is hard to maintain.
Add a `CompactedPartitionedTopic` class as the abstraction to read or write a compacted partitioned topic with the following public APIs:
- sendAsync: write a key-value as well as the timestamp to a partition
- readToLatest: read until the latest message of a partition
- remove: remove the cached producer and reader of a partition
- close: close the resources
Then, use this class to replace the existing offset topic I/O logic in `GroupMetadataManager`.
Add a `CompactedPartitionedTopicTest` to simulate sending messages and reading message before or after the compaction.
Before this PR, when the `GroupMetadataManager` reads the offset topic, it writes an empty …

[refactor] Decoupling the offset topic I/O from GroupMetadataManager

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*
Fixes #1875
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*
Master Issue: #<xyz>
When the Kafka Producer sets acks=0 to send messages to KoP, an error will be throw
not respone for PRODUCE when acks=0
*(Please pick either of the following options)*
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*
Need to update …

[fix] not respone for PRODUCE when acks=0

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/NamespaceBundleOwnershipListenerImpl.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicEventListenerImpl.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicOwnershipListener.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java

Cherry-pick: https://github.com/datastax/starlight-for-kafka/pull/67 
The new TopicEventListener API allows a ProtocolHandler to be notified about the lifecycle of single topics.
Previously we could rely only on Bundle level notifications: loadBundle and unloadBundle.
The old approach had some limitations:
* it didn't support single topic unload (pulsar-admin topics unload TOPIC)
* it didn't support clearing caches in case of topic deletion
* for each bundle we had to eagerly force listing all the topics in the "onLoad" event (this also happened for all the system namespaces in the broker)
* for each bundle we eagerly forced listing of all the topics even in the case of "unload" events
Benefits:
* we will be able to react to single topic events
* we won't need to list all the topics in …

[improvements] Use the TopicEventListener API

---

docs/configuration.md
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopic.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetConfig.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetTopicWriteTimeoutTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopicTest.java

When Kafka writes to offset topics, the default timeout is 5 seconds and it's configurable by the `offsets.commit.timeout.ms` config, while the timeout of KoP is 30 seconds, which could be too long.
- Add an `offsetCommitTimeoutMs` config to configure the offset commit timeout whose default value is 5000.
- Handle the write error in a correct way:
- For already closed exception, return `NOT_COORDINATOR` to tell the Kafka client to retry committing.
- For timeout excepetion, return
- `REBALANCE_IN_PROGRESS` for group messages
- `REQUEST_TIMED_OUT` for offset messages
- For other errors, return `UNKNOWN_SERVER_ERROR` to avoid retrying
- Add `OffsetTopicWriteTimeoutTest` to protect the changes …

Reduce the offset commit timeout to 5 seconds and make it configurable

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetTopicWriteTimeoutTest.java

Even if the session timeout is only 1ms, there is still a chance that the write does not time out.
Run each test in `OffsetTopicWriteTimeoutTest` 10 times and check the errors could only be the expected error or just `NONE`.

Fix flaky OffsetTopicWriteTimeoutTest

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PendingRequest.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java

This PR is cherry-picking from https://github.com/datastax/starlight-for-kafka/commit/e0636995
Complete the pending request features when the channel is Inactive, or the exception caught.

[transactions] Better handling of network exceptions while sending TX markers

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java

(cherry picked from commit fa63a4ab278012ae83319ba2690e201013f2245b)
This PR is used to cherry-pick the commit https://github.com/datastax/starlight-for-kafka/commit/fa63a4ab278012ae83319ba2690e201013f2245b.
The String.format() is an expensive operation in the method canConsumeAsync.
Remove the String.format() operation.

[improvement] Remove expensive useless String.format() in canConsumeAsync

---

tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java

When running `GroupMetadataManagerTest`,
`testOffsetWriteAfterGroupRemoved` will be called after `testOffsetTopicNumPartitionsModify`, which changes the `offsetTopicNumPartitions` to 100 so that `consumerGroupPartitionId` will be 74 while `groupPartitionId` is 0, and then the group metadata will be sent to partition 0 while `scheduleLoadGroupAndOffsets` will read from partition 74. Since no group metadata is loaded,
Migrate the fix in https://github.com/streamnative/kop/pull/1759 to reset the `offsetTopicNumPartitions` before and after each method.

[branch-2.11] Fix failed GroupMetadataManagerTest

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaRequestUtils.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaResponseUtils.java
kafka-impl/src/main/java/org/apache/kafka/common/requests/ListOffsetRequestV0.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaCommonTestUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthBearerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/saslplain/SaslPlainEndToEndTest.java

Upgrade Kafka client version to 2.1.1

[branch-2.10.4] Upgrade kafka client version to 2.1.1

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/ResourceType.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerSaslServer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfig.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientCredentialsFlow.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientInfo.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthLoginCallbackHandler.java
oauth-client/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfigTest.java
oauth-client/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientCredentialsFlowTest.java
oauth-client/src/test/resources/private_key_with_group_id.json
tests/src/test/java/io/streamnative/pulsar/handlers/kop/HydraOAuthUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthKopHandlersTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthKopHandlersWithGroupIdTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java

Currently, the KoP only supports checking the topic permission when doing the consume authorization, but Kafka support checking the topic and group ID permission.
Before introducing this change, let's understand why KoP can't check group ID permission.
When Kafka does the consume authorization check, it will first check the group ID permission in `handleJoinGroupRequest` method, then it will check the topic permission in the `handleFetchRequest` method.
However, Pulsar is using another way to check consume permission. See the
`org.apache.pulsar.broker.authorization.AuthorizationService#canConsumeAsync` method, it requires passing the topic name and subscription to check both permissions in the same place, and the topic name is required param.
```
public CompletableFuture<Boolean> …
```

[branch-2.10.4][improve] Pass group ID to authorizer when using OAuth (#1926)

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java

Handle correctly NOT_LEADER_OR_FOLLOWER while writing TX markers.
Handle BROKER_NOT_AVAILABLE in TransactionMarkerRequestCompletionHandler.

[fix][transaction] Handle errors while writing transaction logs and markers

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/AppendRecordsContext.java

(cherry picked from commit 0b6fd77c0759c54d92ac5aee9b585d1c71c88712)
AppendRecordsContext cannot be Recyclable.
Don't recycle the AppendRecordsContext.

[bugfix] AppendRecordsContext cannot be Recyclable

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicLookupService.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManagerSharedState.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java

(cherry picked from commit f6e7e823159fcb1ac1a1d9201fb6b45172601a24)
Do not use a static LOOKUP_CACHE.

[improvement] Do not use a static LOOKUP_CACHE

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionConfig.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PulsarPartitionedTopicProducerStateManagerSnapshotBuffer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PulsarTopicProducerStateManagerSnapshotBuffer.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PulsarPartitionedTopicProducerStateManagerSnapshotBufferTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PulsarTopicProducerStateManagerSnapshotBufferTest.java

(cherry picked from commit 0e0d235a1fff2882ecdf56e01f80469c1f1ff414)
Use `PulsarPartitionedTopicProducerStateManagerSnapshotBuffer` instead of `PulsarTopicProducerStateManagerSnapshotBuffer`.

[transactions] Do not use a partitioned Reader

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ssl/SSLUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/KafkaSSLChannelTest.java

(cherry picked from commit 5ff8b8079c60e6566175faa9640a2312bd95496d)
Communications between broker inherit BrokerClient configuration.

[security] Communications between broker inherit BrokerClient configuration

---

docs/configuration.md
docs/security.md

https://github.com/streamnative/kop/pull/1728 Introduced tenant for OAuth, and https://github.com/streamnative/kop/pull/1926 introduced group ID for OAuth, we should add docs.

[docs] Add docs for OAuth credentials

---

.github/workflows/pr-tests.yml

After https://github.com/streamnative/kop/pull/1925, the surefire artifacts won't be uploaded if tests failed.
Upload the surefire artifacts when tests failed.

[CI] Upload surefire artifacts when tests failed

---

oauth-client-shaded-test/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfigTest.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfig.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/DataURLStreamHandler.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/PulsarURLStreamHandlerFactory.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/URL.java
oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/package-info.java

The KoP documentation shows the `auth.credentials.url` support decoding base64 format string: `data:application/json;base64,[base64-encoded value]`, but it unsupported yet. 
Support decode base64 format credentials URL

[improve][oauthclient] Support decode base64 format credentials URL

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/SaramaCompressedV1Records.java

When Sarama producers send messages to KoP with message set, e.g.
```golang
conf := sarama.NewConfig()
conf.Version = sarama.V0_10_2_2
conf.Producer.Compression = sarama.CompressionLZ4
producer, err := sarama.NewAsyncProducer([]string{"localhost:15003"}, conf)
```
The `PartitionLog#analyzeAndValidateRecords` method could parse a wrong `LogAppendInfo#numMessages` result. It's because this method uses `RecordBatch#lastOffset` to get the latest offset.
https://github.com/streamnative/kop/blob/3b22e79764ca22107228ec2f74590f0769bd9fd9/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java#L1028
However, when Sarama client handles the message set (v0 or v1 records), it only writes a offset of zero value: …

Fix wrong offset increment for Sarama message set

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionTest.java

Most of the tests in `TransactionTest` take at least 10 seconds because the `request.timeout.ms` config is 10000. See
https://github.com/streamnative/kop/blob/1fd3bdb9158fd944c2fb7a241c0d8dca923367ab/tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionTest.java#L1150
It's because KoP loads the metadata topic lazily, unlike Kafka, which loads the metadata topic when started. KoP adopts this way because KoP starts before the Pulsar broker finishes the start, in this case there might be some problems with the topic lookup.
Therefore, when the Kafka producer sends the 1st INIT_PRODUCER_ID request, it will receive `COORDINATOR_LOAD_IN_PROGRESS` error, and the request will reenqueue [1], then the request will expire after `request.timeout.ms` milliseconds. …

[Transaction] Fix initTransaction might wait until request timeout

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/exceptions/KoPTopicInitializeException.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaResponseUtils.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
kafka-impl/src/main/java/org/apache/kafka/common/requests/ResponseCallbackWrapper.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeKafkaFormatTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaCommonTestUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/admin/KafkaAdminTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/e2e/DistributedClusterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/metrics/MetricsProviderTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/GlobalKTableTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KStreamAggregationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KTableTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KafkaStreamsTestBase.java

(cherry picked from commit 71b77b2fd65fd1a2d481ed7067939fab3c0ad002)
Update Kafka wire protocol to 3.4.0 and implement KIP-699 and KIP-709.
*Describe the modifications you've done.*

Update Kafka wire protocol to 3.4.0 and implement KIP-699 and KIP-709

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManager.java

Handle some failures while writing transaction logs and markers.

[fix][transaction] Handle some failures in transaction

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java

In PR https://github.com/streamnative/kop/pull/1943 , it introduced using UUID to distinguish deleted/created topics, but when the topic is auto-created, the UUID is not contained in the properties.
Contains UUID when auto topic creation

[fix][transaction] Contains UUID when auto topic creation

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicLookupService.java

`testMultiBrokerUnloadReload` is flaky with the Pulsar dependency upgraded to 3.1.0-SNAPSHOT. Here are the related logs:
```
02:37:33.275 [pulsar-ph-kafka-644-3:io.streamnative.pulsar.handlers.kop.KafkaTopicLookupService@105] ERROR io.streamnative.pulsar.handlers.kop.KafkaTopicLookupService - [io.streamnative.pulsar.handlers.kop.storage.PartitionLog@131e450c] Failed t
o getTopic persistent://public/default/kopMultiBrokerUnloadReload10-partition-3. exception:
java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException:
```
It's because the exception passed from `BrokerService#getTopic` is `CompletionException`, not `ServiceUnitNotReadyException`, while KoP does not get the cause of a `CompletionException` in …

Fix topic lookup failed exceptionally with ServiceUnitNotReady

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/DataSketchesOpStatsLogger.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/LocalData.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusMetricsProvider.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/ThreadLocalAccessor.java

Fixes #1956
FastThreadLocal wont cleanup until thread exit. so we can just check if the stats is not recorded a long time if expired just remove from threadlocal
add time check logic if long time have no record just remove the stats.

Add Time based metric exipration.

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterFactory.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java

We should use pulsar format to encode the marker when writing into the `__consumer_offsets` topic, otherwise it will have the following errors:
```
2023-08-09T09:17:18,398+0000 [pulsar-client-io-69-3] ERROR org.apache.pulsar.client.impl.ConsumerImpl - [public/__kafka/__consumer_offsets-partition-42][reader-ca0ccccd79] Discarding corrupted message at 6:5
2023-08-09T09:17:18,402+0000 [pulsar-client-io-69-3] WARN  org.apache.pulsar.client.impl.ConsumerImpl - [reader-ca0ccccd79] [98942] unable to obtain message in batch
java.lang.IllegalStateException: java.lang.IllegalStateException: Some required fields are missing
```
Use pulsar format when write marker to __consumer_offsets topic
(Please …

[fix][transaction] Use pulsar format when write marker to __consumer_offsets topic

---

docs/configuration.md
kafka-impl/pom.xml
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaAuthorizationMockTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaAuthorizationMockTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SlowAuthorizationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/SaslOAuthKopHandlersTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/SaslOAuthKopHandlersWithMultiTenantTest.java

To follow Kafka's behavior, KoP also performs authorization for each PRODUCE or FETCH request. If the custom authorization provider is slow to authorize produce or consume permissions, the performance will be impacted.
Introduce caches for authorization:
- PRODUCE: (topic, role) -> result
- FETCH: (topic, role, group) -> result;
Add `SlowAuthorizationTest` to verify the producer and consumer won't be affected significantly by slow authorization.
Introduce two configs to configure the cache policy so that revoke permission can work:
- kopAuthorizationCacheRefreshMs: the refresh timeout
- kopAuthorizationCacheMaxCountPerConnection: the max cache size
(If this PR contains …

Optimize authorization by caching authorization results

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingTopicFutures.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/AppendRecordsContext.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EncodePerformanceTest.java
kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogTest.java

Fix: https://github.com/streamnative/kop/issues/1956
Update stats on the netty threads to fix the stats memory leak issue.
The root cause is we can only use `DataSketchesOpStatsLogger` in the netty thread. When used in other threads, it will cause memory leak, since the `FastThreadLocal` can't remove the map if the thread is not netty thread.

[fix] Memory leak of the map in ThreadLocalAccessor

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java

https://github.com/streamnative/kop/pull/1923 removes the completion for the produce purgatory in https://github.com/streamnative/kop/pull/1749.
Added back the logic to check and complete the produce purgatory.

Fix the regression for https://github.com/streamnative/kop/pull/1749

---

kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java

Both the response thread and timeout detection thread will access PendingProduceCallback
This problem will easily occur when the sending latency is close to the timeout threshold.
Step-1： response thread and timeout detection thread access 1 at the same time, none of them meet the conditions for return
Step-2: timeout detection thread execute to 2, and set responseMap = null
Setp-3: response thread execute to 3,  cause NPE
Add synchronized

Fix unknown exception caused by thread safety issue
